### ISSUE TITLE
Panic with 'byte index 32 is not a char boundary' error

### ISSUE THREAD

**Issue by saks** [awslabs/aws-lambda-rust-runtime#100]
Our lambda fails on certain SNS messages. I found that every message involved has some special characters like `😊`, `👌🏻`, `☺`(codepoint is 9786) , `’`(codepoint 8217) and others.
In different form: `'here \ud83d\ude0a my fianc\u00e9 '`.

The error message looks like this:
```
thread 'main' panicked at 'byte index 32 is not a char boundary; it is inside '☺' (bytes 31..34) of `And perfect, thank you so much!☺️`', src/libcore/str/mod.rs:2102:5
RequestId: 855396e8-00b6-4029-9843-80e67960813e Error: Runtime exited with error: exit status 101
Runtime.ExitError
```

**Comment by softprops** [comment]
What client or interface you're using to trigger this messages with?

**Comment by softprops** [comment]
Also, can you paste an example of what your handler looks like?

**Comment by saks** [comment]
Sorry, fortunately this is me not dealing with chars properly. Apologies for the false alarm.
