### ISSUE TITLE
How to access event values?

### ISSUE THREAD

**Issue by l1x** [awslabs/aws-lambda-rust-runtime#101]
Maybe I missing the point here but I am new to Rust and not sure how to do the following, which is our Python code that we are trying to port:

```Python
def handler(event, context):
    print(event)
    event_type = event.get('resource', 'not_found')
    http_method = event.get('httpMethod', 'not_found')
    try:
        if event_type=='not_found' or http_method=='not_found':
            ret['statusCode']=404
            ret['body']=json.dumps({'err': 'err', 'event_type': event_type, 'http_method': http_method })
        elif event_type=='/echo':
            ret['statusCode']=200
            ret['body']=json.dumps(event, default=str)
        elif event_type=='/user/{username}' and http_method=='GET':
            response = client.get_user(
                UserName=event['pathParameters']['username']
            )
            ret['statusCode']=response['ResponseMetadata']['HTTPStatusCode']
            ret['body']=json.dumps(response, default=str)
```

This code relies on accessing resource and httpMethod which are defined in the event. Would it be possible to deserialize selected values into the CustomEvent struct that is in the example code?

```Rust
#[derive(Deserialize)]
struct CustomEvent {
    #[serde(rename = "firstName")]
    first_name: String,
}
```

Thanks in advance.

**Comment by saks** [comment]
hey @l1x, do I understand correctly that your lambda is triggered by http request (API Gateway)?

**Comment by l1x** [comment]
I guess this is exactly what I am wondering about. Where I am lost is, when do I use Request vs. CustomEvent. Not sure if I could serialize into a CustomEvent the keys from the Request so that I have a struct to handle in my handler. Maybe I need to serialize the data into a CustomEvent and also have Request passed into my request? I guess I am trying to understand what is the best way of achieving that.  Thanks for the Request hint I can already move forward with this.

**Comment by saks** [comment]
If you really want custom event, you can use [this](https://dev.to/robertohuertasm/aws-lambda-functions-written-in-rust-3bob) approach.
Personally, if I deal with http request, I prefer to not bother and just use default request structure.

**Comment by l1x** [comment]
Hi @saks, finally I got to the point when I can write Lambda handlers in Rust. After reviewing the library source and examples almost all examples use CustomEvent to deal with HTTP requests. What do you mean by default request structure in your previous comment? Could you show me an example?

**Comment by saks** [comment]
hey @l1x, I meant that if you're using lambda as API Gateway, then it's much easier to use [Request](https://docs.rs/lambda_http/0.1.1/lambda_http/type.Request.html) type comparing to custom data structure ([example](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-http/examples/basic.rs#L15)).

**Comment by l1x** [comment]
@saks excellent thank you very much, I just implemented my first Lambda using that. Much appreciated.

**Comment by saks** [comment]
No worries @l1x, any time! We've implemented quite a number of API gateways in rust, so feel free to ask if you have any blockers.

**Comment by l1x** [comment]
Thanks @saks it is really appreciated. I would like to grab the opportunity and ask one question.

How do you handle http post body properly?

```Rust
fn user_login(req: Request, _ctx: Context) -> Result<Response<Body>, HandlerError> {
   
    // This is the example code that works:
    //let args: UserLogin = req
    //    .payload()
    //    .unwrap_or_else(|_parse_err| None)
    //    .unwrap_or_default();

   // What if I would like to handle every branch? This does not work
    let args: Result<Option<UserLogin>, PayloadError> = req.payload();

    match args {
        Err(err) => {
            error!("Error: {:?} fn: user_login", err);
            Ok(build_resp(
                format!("{:?}", "Error"),
                StatusCode::INTERNAL_SERVER_ERROR,
            ))
        }
        Ok(user_login_maybe) => match user_login_maybe {
            None => {
                error!("{:?}", "Empty http body");
                Ok(build_resp(
                    format!("{:?}", "Empty http body"),
                    StatusCode::NOT_FOUND,
                ))
            }
            Some(user_login) => {
                info!("{:?}", user_login.email);
                Ok(build_resp(
                    format!("{:?}", user_login.email),
                    StatusCode::OK,
                ))
            }
        },
    }
}
``` 

I can't really find PayloadError

```
use lambda_http::{lambda, Body, IntoResponse, PayloadError, Request, RequestExt, Response};
  |                                               ^^^^^^^^^^^^ no `PayloadError` in the root

```

Let me know what is the right way of doing this. Thanks in advance.

**Comment by l1x** [comment]
There is also a question regarding stateful clients, not sure how to pass that in using the lambda! macro. 

https://users.rust-lang.org/t/how-to-pass-in-stateful-client-to-lambda-function/31043

**Comment by davidbarsky** [comment]
Not addressing the event value question—sorry, running off to an appointment—but there was a recent issue about stateful clients here: https://github.com/awslabs/aws-lambda-rust-runtime/issues/123.

We should probably feature that more prominently in docs.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by l1x** [comment]
Thanks @davidbarsky I already found the solution for that using lazy_static.

**Comment by arahalevich-move** [comment]
hey @l1x, it looks like `PayloadError` is not exposed from `lambda_http`. This may be changed in future, but looking at the implementation, I see that in the case of an error you will always get `Ok(None)`.

Tests for `ext` module are written in the way that they expected `Ok(None)` as well after calling `.unwrap_or_default()` which will "eat" the error type.

I think it is safe to rely on `unwrap_or_default()`.

If you really want to handle potential error that is caused by deserializer, you can use the following approach:
```rust
#[derive(Debug)]
pub enum MyError {
    BadJson(serde_json::Error),
    NoRquestBody,
}

fn user_login(req: Request, _ctx: Context) -> Result<Response<Body>, HandlerError> {
    let args: Result<UserLogin, MyError> = match req.body() {
        Body::Text(text) => serde_json::from_str(text).map_err(MyError::BadJson),
        _ => Err(MyError::NoRquestBody),
    };

    match args {
        Err(MyError::BadJson(err)) => {
            error!("Error: {:?} fn: user_login", err);
            Ok(build_resp(
                format!("{:?}", "Error"),
                StatusCode::INTERNAL_SERVER_ERROR,
            ))
        }
        Err(MyError::NoRquestBody) => {
            error!("{:?}", "Empty http body");
            Ok(build_resp(
                format!("{:?}", "Empty http body"),
                StatusCode::NOT_FOUND,
            ))
        }
        Ok(user_login) => Ok(build_resp(
            format!("{:?}", user_login.email),
            StatusCode::OK,
        )),
    }
}
```

**Comment by l1x** [comment]
Excellent @saks thanks very much. I though I am doing something incorrectly because that error type was not available.
