### ISSUE TITLE
Not working the length function for getting the length of an array value.

### ISSUE THREAD

**Issue by elixirdada** [awslabs/aws-lambda-rust-runtime#104]
I tried to get the length of an array value. So I have coded as below.

```
var unreadCounts = 0;
var unreadMsg = [];

 unreadMsg = dtc_data.Items.map(data => {
      if (data.acknowledged == false)
         return data;
  })

  unreadCounts = unreadMsg.length;
  return cb(null, unreadCounts);
```

I thought it should return the unread count as a number. But I have got an error 

> Internal server error

Doesn't support the length function in the AWS Lambda?

**Comment by saks** [comment]
It looks like your lambda code is written in JavaScript, but this project is aiming to provide a way to implement lambda function in rust programming language.

**Comment by softprops** [comment]
I think we should close this issue out
