### ISSUE TITLE
Environment variable not updating

### ISSUE THREAD

**Issue by jeprojects** [awslabs/aws-lambda-rust-runtime#105]
In the main function using the rust runtime for some reason it is using the original environment variable that I had set in the aws lambda console. Even after 24 hours and several iterations of the function code it still uses the old environment variable.

I am doing this:

`info!("Log level: {}", env!("LOG_LEVEL"));
`

Is there some way to fix this?

**Comment by softprops** [comment]
This is not specific to the the rust runtime but the way that lambda works. It will keep as many number of instances of your lambda "alive" as is needed to serve requests. In periods of lulls this will go down to zero. 

I don't know how long the max amount of time lambda will keep and instance alive but believe what you are seeing is a new instances of the lambda reading your updated func config but are observing previous instances in your logs producing output based in the previous state of your func config. 

Aside, it's tempting to use the console for simple changes but it's usually more reliable to depend on a ci/cd deployment process to update a function's state. I've experimented with using the function env as a ["runtime" config](https://github.com/meetup/lev) but have experienced the same behavior as what's being reported here.

**Comment by bahildebrand** [comment]
@softprops response seems to answer your question. Feel free to re-open this if you're still unsure.
