### ISSUE TITLE
Sharing resources across invocations

### ISSUE THREAD

**Issue by lxwbr** [awslabs/aws-lambda-rust-runtime#123]
Being very new to Rust in general I was wondering how I could share [rusoto](https://github.com/rusoto/rusoto) clients across multiple Lambda invocations. In particular I am trying to cache an IoT Data client for function invocations which happen several times per minute. Coming from Typescript where caching in global scope solves the issue, I can't figure out how to do it in Rust. Apologies if this should be out of scope for this project, but I couldn't find an answer anywhere else.

In this code I would like to cache `iot_data_client` for further invocations:
```
use lambda_runtime::{error::HandlerError, lambda, Context};
use serde_derive::{Serialize, Deserialize};
use rusoto_iot_data::{IotData, IotDataClient, PublishRequest};
use bytes::Bytes;
use rusoto_core::Region;

#[derive(Deserialize, Clone)]
struct CustomEvent {
    first_name: String,
    last_name: String,
}

#[derive(Serialize, Clone)]
struct CustomOutput {
    message: String,
}

fn main() {
    lambda!(my_handler);
}

fn my_handler(e: CustomEvent, _ctx: Context) -> Result<CustomOutput, HandlerError> {
    if e.first_name == "" {
        panic!("Empty first name");
    }
    let request = PublishRequest {
        payload: Some(Bytes::from_static(b"Hello Rust!")),
        topic: String::from("rust"),
        qos: Some(1),
    };
    // How can I cache this?
    let iot_data_client = IotDataClient::new(Region::EuCentral1);
    
    match iot_data_client.publish(request).sync() {
        Ok(_result) => {
            Ok(CustomOutput{
                message: format!("Hello, {}!", e.first_name),
            })
        },
        Err(error) => {
            panic!(format!("Error: {:?}", error))
        }
    }   
}
```

**Comment by davidbarsky** [comment]
No worries! The easiest thing to do would be to place the `IotDataClient` in [`lazy-static`](https://github.com/rust-lang-nursery/lazy-static.rs) or a [`OnceCell`](https://github.com/matklad/once_cell). I'd suggest using `OnceCell`, as you don't need to place the `iot_data_client` behind a Mutex.

I'd also benchmark whether caching `IotDataClient` is _even necessary_, as creating a new `IotDataClient` (which makes use of [hyper::Client](https://docs.rs/hyper/0.12.31/hyper/client/struct.Client.html) underneath) might be faster and cheaper than accessing a client stored in RAM.

**Comment by softprops** [comment]
You could also use a struct whose fields represent your runtime dependencies and impl Handler for that struct

**Comment by lxwbr** [comment]
@davidbarsky thanks for your help, I tried using OnceCell like this and it worked:

```
use lambda_runtime::{error::HandlerError, lambda, Context};
use serde_derive::{Serialize, Deserialize};
use rusoto_iot_data::{IotData, IotDataClient, PublishRequest};
use bytes::Bytes;
use rusoto_core::Region;
use once_cell::sync::OnceCell;

#[derive(Deserialize, Clone)]
struct CustomEvent {
    first_name: String,
    last_name: String,
}

#[derive(Serialize, Clone)]
struct CustomOutput {
    message: String,
}

fn iot_data_client() -> &'static IotDataClient {
    static INSTANCE: OnceCell<IotDataClient> = OnceCell::new();
    INSTANCE.get_or_init(|| {
        IotDataClient::new(Region::EuCentral1)
    })
}

fn main() {
    lambda!(my_handler);
}

fn my_handler(e: CustomEvent, _ctx: Context) -> Result<CustomOutput, HandlerError> {
    if e.first_name == "" {
        panic!("Empty first name");
    }

    let request = PublishRequest {
        payload: Some(Bytes::from_static(b"Hello Rust!")),
        topic: String::from("rust"),
        qos: Some(1),
    };
    
    match iot_data_client().publish(request).sync() {
        Ok(_result) => {
            Ok(CustomOutput{
                message: format!("Hello, {}!", e.first_name),
            })
        },
        Err(error) => {
            panic!(format!("Error: {:?}", error))
        }
    }  
}
```

From a quick smoke test it actually helps. Here are the times before the change:
![image](https://user-images.githubusercontent.com/6862750/60919811-eeff1780-a296-11e9-8581-167df0d879c7.png)

And here after the change:
![image](https://user-images.githubusercontent.com/6862750/60919842-02aa7e00-a297-11e9-9b44-53b7f77d5d75.png)

@softprops still at the very beginning of learning Rust and am not quite sure how to do that, but will give it a try as soon as I am that far.

**Comment by lxwbr** [comment]
Thanks for the help, I will close this issue as it is resolved for my testing purposes.

**Comment by softprops** [comment]
@lxwbr those graphs look awesome
