### ISSUE TITLE
Payload error lost

### ISSUE THREAD

**Issue by kunicmarko20** [awslabs/aws-lambda-rust-runtime#125]
Hi all, correct me if I am wrong but:

https://github.com/awslabs/aws-lambda-rust-runtime/blob/0ac259a711d6486e7f6b7dc641539fbec1ee7b79/lambda-http/src/ext.rs#L226

Based on this, if the payload deserialization fails, you return `Ok(None)` losing the original error message, basically the response will always be Ok and never PayloadError?

**Comment by softprops** [comment]
In your test, is the client sending an accept HTTP header?

**Comment by kunicmarko20** [comment]
Yes, the content-type was there and it was failing but I couldn't see why, in the end I did manual deserialization and then I saw the error.

**Comment by kunicmarko20** [comment]
My issue was that the deserialization was failing and I was getting `Ok(none)` which didn't tell me why. I was just wondering if this is expected and right way to do this?

Also, the return type is ` -> Result<Option<D>, PayloadError>` but it will never be `PayloadError`? because of `unwrap_or_else`?

I would rather have the error message and log it or something and know what happened instead of getting `Ok(None)`
