### ISSUE TITLE
gateway bindings

### ISSUE THREAD

**Issue by srijs** [awslabs/aws-lambda-rust-runtime#13]
Hi!

It's great to see official lambda support for Rust!

Over at https://github.com/srijs/rust-aws-lambda, we have been building a lambda runtime and various auxiliary crates. We will start to redirect users of the runtime parts over to the official runtime, but similar to #12 I'm keen to hear whether there is interest on your side to move some of the other auxiliary crates.

In particular, there are bindings that translate between the API Gateway proxy events and the types provided by the `http` crate. I'm happy to continue to provide these myself, but I'd like to avoid any duplication of effort, so if you'd like to incorporate these please let me know!

**Comment by davidbarsky** [comment]
> Over at https://github.com/srijs/rust-aws-lambda, we have been building a lambda runtime and various auxiliary crates. We will start to redirect users of the runtime parts over to the official runtime, but similar to #12 I'm keen to hear whether there is interest on your side to move some of the other auxiliary crates.

> In particular, there are bindings that translate between the API Gateway proxy events and the types provided by the http crate. I'm happy to continue to provide these myself, but I'd like to avoid any duplication of effort, so if you'd like to incorporate these please let me know!

We'd be super happy to accept any auxiliary crate from rust-aws-lambda! I'd also like to explore how we can support how Lambda accepts HTTP requests as a target of an [Application Load Balancer](https://aws.amazon.com/blogs/networking-and-content-delivery/lambda-functions-as-targets-for-application-load-balancers/). I suspect the interaction would be pretty similar.

**Comment by phillyfan1138** [comment]
So does this official library not support http events yet?

**Comment by sapessi** [comment]
No @phillyfan1138, this library only takes care of interacting with the Runtime APIs and start your handler function. To handle API Gateway proxy events or ELB requests you'd need to provide your structs that mirror the event types. Take a look at [this crate](https://github.com/srijs/rust-aws-lambda/tree/master/aws_lambda_events). We are exploring taking this over in the future (#12)

**Comment by srijs** [comment]
Yay, good job @softprops!
