### ISSUE TITLE
Compiling lambda_runtime_errors v0.1.1 ERROR

### ISSUE THREAD

**Issue by MendesJ** [awslabs/aws-lambda-rust-runtime#175]
Hello,

When compiling my project that uses:

`lambda_runtime = "^0.2"`
`rusoto_core =  "^0.42"`

I get 2 errors when compiling `lambda_runtime_error v0.1.1`:

- `error[E0277]: the trait bound (): LambdaErrorExt is not satisfied`--> `$HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/lambda_runtime_errors-0.1.1/src/error_ext_impl.rs:145:9`

- `error[E0277]: the trait bound `(): std::error::Error` is not satisfied` -->
`$HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/lambda_runtime_errors-0.1.1/src/error_ext_impl.rs:145:9`

Cargo version: `cargo 1.41.0-nightly (8280633db 2019-11-11)`
Rustc : `rustc 1.41.0-nightly (412f43ac5 2019-11-24)`

It seems that it is related to the `nightly` version since it worked perfectly 3 days ago and doesn't work since I run `rustup update`.

**Comment by davidbarsky** [comment]
Hrm, thanks for the report. That's... not great. I'm not 100% sure what the cause is, but I think the relates to `!` being stabilized around that type. As a result, type inference for `()` and `!` changed.

**Comment by MendesJ** [comment]
Thanks for your feedback.

Until the end of the year, I haven't the time to do it. I'm doing my Master Thesis which is extremely time-consuming. If someone else could fix it, until then, it would be great. Otherwise, I will look into it, in January.

**Comment by d0nutptr** [comment]
Would you want to also remove the bounds on `Fail`? It appears to be used to dump backtraces of errors. I'm currently working on a temporary change that removes all of the error code and limiting the bound to `Send + Sync` (for threading reasons) and would be willing to share a PR given the warning that I'm not keeping `Fail` (if it's in the final version, that's fine; I just don't care for it and it makes this change easier due to the usage of `?` and `serde_json` functions.

**Comment by tsal** [comment]
I'm not sure if it's related, but this seems to no longer fail (it did for me when I checked a month ago).  Even without #182 being merged.

```
Finished dev [unoptimized + debuginfo] target(s) in 38.75s
cargo 1.41.0-nightly (626f0f40e 2019-12-03)
rustc 1.42.0-nightly (0de96d37f 2019-12-19)
```

Granted, I'm not using the `lambda_runtime_error` crate.

**Comment by davidbarsky** [comment]
@tsal missed that fix, oops. the stabilization of `!` got reverted, so this issue can probably be closed.

**Comment by MendesJ** [comment]
I modified my implementation so I can use the `stable` toolchain instead. I  tried to compile with the `nightly (cargo 1.42.0-nightly (6e1ca924a 2020-01-06))` toolchain and it worked too.
So as suggested by @davidbarsky  I closed the issue.
