### ISSUE TITLE
X-Ray Support

### ISSUE THREAD

**Issue by henriiik** [awslabs/aws-lambda-rust-runtime#223]
Hello!

It would be great to have some easy way to get data into AWS X-Ray, and I am willing to help make it happen.

I searched the issues and found some references some potential future support, do you think it is a good fit for this project?

**Comment by softprops** [comment]
@henriiik x-ray tracing is not specific to a language runtime. 

As a product integration feature you can turn on active tracing by [checking a box in your aws lambda console](https://docs.aws.amazon.com/xray/latest/devguide/xray-usage.html)

**Comment by henriiik** [comment]
Yes, of Courteney. I meant sending additional trace data To X-Ray. But I suppose it would an external crate would be more fitting.

**Comment by brainstorm** [comment]
@henriiik I suspect you are looking for things like these?:

https://github.com/tokio-rs/tracing
https://github.com/davidbarsky/tracing-xray
