### ISSUE TITLE
'env_logger::init should not be called after logger initialized

### ISSUE THREAD

**Issue by xiao-pp** [awslabs/aws-lambda-rust-runtime#227]
Hi,

My main function looks like:
```rust
#[lambda]
#[tokio::main]
async fn main(event: Value) -> Result<(), Error> {
    env_logger::init();
    debug!("event received: {}.", event);
    some_async_invocation(event).await
}
```

After uploading the binary, first call to Lambda is always good, from second call it panics:
```
thread 'main' panicked at 'env_logger::init should not be called after logger initialized: SetLoggerError(())'
```

I thought each invocation to the Lambda function should be isolated? Or something in the runtime I don't really understand.

Thanks in advance.

**Comment by softprops** [comment]
This is expected though it could benefit from more documentation.

The `lambda_http` module documents tradeoffs of using the lambda attribute [here](https://github.com/awslabs/aws-lambda-rust-runtime/blob/91d2a60d4a0d040332521576f9ac349add3db128/lambda-http/src/lib.rs#L21). The same rules apply for the core lambda crate.

You have a few options.

1) use a [plain main, sans-macros](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda/examples/hello-without-macro.rs) this will do exactly what you expect with no overhead.

2) use the [try_init](https://docs.rs/env_logger/0.7.1/env_logger/fn.try_init.html) fn on `env_logger` and ignore the error after its first invocation. This variant is useful when you lack control over the way a rust application is bootstrapped. In the case of lambda, you have options for cases needing initialization control (see above)

3. Use a crate for lazy static initialization. 

To explain the behavior you are seeing this [lambda documentation](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-context.html) might be helpful.

Lambda the execution env creates tasks on demand to handle invocations (executing your handler code in the process) in most these tasks have some amount of lifetime before they are destroyed. Lambda will create as many of these tasks as needed to fulfill your workload for you. It keeps tasks around for short amount of time to recycle a "warm" function where it can for reduced latency. As a lambda user it's good to be mindful of the implications of this. I'm cases where your function requires some initialization that should happen only once (your case is a good example) you'll want to structure your lambda accordingly.

Hope that helps!

**Comment by xiao-pp** [comment]
That explains it - appreciate for the detailed answer! `try_init` does the job 👍
