### ISSUE TITLE
Please make/derive a StrMap builder so it can unit tested locally

### ISSUE THREAD

**Issue by y2kappa** [awslabs/aws-lambda-rust-runtime#230]
Happy to take this if you think it's valid. 

I am developing on Mac and it's extremely difficult to test the http handlers being called from an android app. I used to have serverless offline or even tried serverless localhost but they all fail in different manners so I decided to mock the entry point with my own http server and have a common handler for get and post requests. In the get case it takes the StrMap and in Post it takes a String from body. However I need to be able to unit test. 

Trying to build it like in the unit tests fails with ^^^^^^ constructor is not visible here due to private fields

**Comment by softprops** [comment]
You should be able to derive one from a HashMap
 
https://github.com/awslabs/aws-lambda-rust-runtime/blob/91d2a60d4a0d040332521576f9ac349add3db128/lambda-http/src/strmap.rs#L56

**Comment by y2kappa** [comment]
It's private, you can't call it. See the error I posted above:
```
^^^^^^ constructor is not visible here due to private fields
```

**Comment by y2kappa** [comment]
I only managed to build one by forking this repo and referring to it using the path attribute in cargo toml and removing the `test` cfg attribute for the `with_query_string_parameters` function. Which means i need to keep a local mirror of this repo if I want to have unit testing which is less than ideal.

**Comment by softprops** [comment]
Sorry I wasn't clear. Since StrMap implements from `HashMap<String,Vec<String>>`, you should be able to call `StrMap::from(your_hash_map)` . The unit tests don't have a good example of this atm

**Comment by y2kappa** [comment]
That worked, thanks! sorry, not sure why I got the error the first time.

**Comment by softprops** [comment]
No worries. Happy to help
