### ISSUE TITLE
Thoughts about deadline API

### ISSUE THREAD

**Issue by Sh4rK** [awslabs/aws-lambda-rust-runtime#24]
First, there is some inconsistency about what the deadline values mean: here
https://github.com/awslabs/aws-lambda-rust-runtime/blob/109a54770f25830fdd663a2d4cd46504bd72b1d0/lambda-runtime/src/context.rs#L62-L64
and here
https://github.com/awslabs/aws-lambda-rust-runtime/blob/109a54770f25830fdd663a2d4cd46504bd72b1d0/lambda-runtime-client/src/client.rs#L101-L102
the comments state that the timestamp is in nanoseconds, but here (and in the tests below)
https://github.com/awslabs/aws-lambda-rust-runtime/blob/109a54770f25830fdd663a2d4cd46504bd72b1d0/lambda-runtime/src/context.rs#L103-L108
it is used as if it's actually milliseconds. Which one is correct?

Second, I don't think we need `u128` for the deadlines, even if they are in nanoseconds; an `u64` would last until the year 2554, and even an `i64` until the year 2262. Also, we should probably use a signed int (`i64`) for the return value of `get_time_remaining_millis`. What do you think?

I can open a PR for these if we come to any conclusions.

 (Sorry for using "we" when I clearly haven't done anything for the project yet, it was the easiest to phrase it this way.)

**Comment by sapessi** [comment]
Agree on u64. The deadline is actually millis - used to be nanos. I forgot to change the comments. Love the "we" - we've been blown away by the community engagement.

**Comment by Sh4rK** [comment]
Closed accidentally.

**Comment by Sh4rK** [comment]
So with #27 merged, I've been thinking about directly exposing the deadline, either in milliseconds or as a `chrono` datetime value. However, I don't actually need that (right now), it's more like a "why not?" idea, so feel free to close this issue.

**Comment by coltonweaver** [comment]
@Sh4rK let us know if you still feel strongly about this issue. In the meantime I'm going to close this, but feel free to reopen it.
