### ISSUE TITLE
Runtime failed to start: fork/exec /var/task/bootstrap: exec format error

### ISSUE THREAD

**Issue by torntrousers** [awslabs/aws-lambda-rust-runtime#25]
Hello. I'm trying this, following whats in the README and getting to the step```aws lambda invoke``` for the basic example and it fails with:
```
RequestId: 22649496-f719-11e8-b4b6-c796ae152b7e Error: Runtime failed to start: fork/exec /var/task/bootstrap: exec format error
Runtime.ExitError
```
Any ideas?

**Comment by sapessi** [comment]
Hey @torntrousers, I suspect because the target platform. If you are using a Mac, you can follow the [tutorial here](https://aws.amazon.com/blogs/opensource/rust-runtime-for-aws-lambda/). Otherwise, use an Amazon Linux Docker container - I posted a [Dockerfile definition here](https://github.com/awslabs/aws-lambda-rust-runtime/issues/17#issuecomment-443558236)

**Comment by torntrousers** [comment]
Thanks, I am using a Mac and I followed that tutorial and was able to get the basic example working. Yay! It wasn't totally straight forward though and needed a few attempts to fix it. I'll see if can write up the minimal steps. Might be good to mention the building on a Mac complications in the README here.

**Comment by TheSriram** [comment]
Ran into this transiently on windows too, with another custom runtime.

**Comment by softprops** [comment]
If you are a [serverless framework](https://serverless.com/framework/) user you may want to check out the [rust plugin](https://github.com/softprops/serverless-rust) It provides a more seemless build experience as it uses the lambdaci project's "provided" build env ( a faithful replication of the same env you will be deploying into )

**Comment by AnjaneyuluBatta505** [comment]
for me, it's the problem with the platform. I was on mac with an m1 chip. After setting the **architecture** to `**x86_64**` worked for me.
