### ISSUE TITLE
Handling serde_json::from_slice errors

### ISSUE THREAD

**Issue by taylor1791** [awslabs/aws-lambda-rust-runtime#257]
As far as I can tell, there is no way to handle request bodies that [Serde fails to deserialize](https://github.com/awslabs/aws-lambda-rust-runtime/blob/f40461785625d8ac23e7c248367b1d724ef2b5ba/lambda/src/lib.rs#L209). In my case, I simply want to log it (and till fail the invocation), but another might want to manually put it in a dead letter queue.

 1. Did I overlook something?
 2. If this a desirable feature and you have an API in mind, I am happy to try and implement it.

**Comment by rimutaka** [comment]
@taylor1791 , we have PR #244 that addresses this issue sitting in the queue. It's been there for a while. You can use https://github.com/rimutaka/aws-lambda-rust-runtime/tree/davidbarsky/update-readme branch to get the error logging.
We've been using that branch for some weeks now. I'll be on standby if you run into any problems with it.

**Comment by taylor1791** [comment]
@rimutaka I was able to get that branch to serve all of my needs. Thank you for your guidance.

🤞 that the MR will land on master soon.
