### ISSUE TITLE
Rust library for the Lambda Extensions API?

### ISSUE THREAD

**Issue by nmoutschen** [awslabs/aws-lambda-rust-runtime#261]
AWS Lambda now support [extensions](https://aws.amazon.com/blogs/compute/introducing-aws-lambda-extensions-in-preview/). To improve the developer experience, it'd be nice to have a library similar to this but that handle the [Extensions API specific calls](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html).

It'd be nice to have something that works in the same way as the `lambda-runtime` but for the extension API, so that people could use Rust for creating Lambda extensions.

**Comment by rimutaka** [comment]
@nmoutschen , correct me if I'm wrong, but neither runtime nor functions interact with the extensions directly, so there is no change to the runtime. Right?

The Extensions API seems to be similar to the runtime API. It should be possible to port the runtime code to make an extension.
I can't think of any use case for an extension other than logging or monitoring. Any real life examples outside of what is already in AWS docs?

**Comment by nmoutschen** [comment]
Hey @rimutaka !

That's correct, there's no change to the runtime. Here the idea would be to create a new create (e.g. `lambda-extension`) that would make it easier to create extensions in Rust.

There are some use-cases around pre-fetching parameters that are changing too frequently to be exposed through environment variables. Doing so via extensions would allow async fetching outside of the main call path. I was also thinking about sending events asynchronously after a Lambda function has returned (e.g. you'd have APIGW -> Lambda, but you could asynchronously send to EventBridge). That said, lowering the barrier for entry would help a lot with developing more use-cases for this.

The rationale behind having a library for Rust is that, Rust being a compiled language, it's easier to create layers that can be used in all runtimes that supports the Extensions API.

**Comment by rimutaka** [comment]
@nmoutschen , I'll be happy to contribute if someone takes the lead. Take a look at https://github.com/rimutaka/aws-lambda-rust-runtime. It is based on some good work @davidbarsky put in earlier this year in a separate branch. It may be better to base any further development on that because it has better logging and a few other improvements.
