### ISSUE TITLE
Thoughts on HTTP/2 Support?

### ISSUE THREAD

**Issue by SilentCicero** [awslabs/aws-lambda-rust-runtime#275]
Hi there,

Any thoughts on supporting HTTP/2 at all?

Not sure how this would change the existing configuration, but would likely improve performance for binary communication.

**Comment by softprops** [comment]
I believe this would/should happen in the connection management layers that sit above your lambda like API Gateway and ALBs. Your lambda fires in response to a connection to produce an http response but not to manage one of those connections. Some of these connection managers transparently handle http2 connections for you.

If your application requires more connection management control you might want to check out aws fargate.

**Comment by coltonweaver** [comment]
I think @softprops answer covered this sufficiently. Feel free to reopen if you still have questions.
