### ISSUE TITLE
Update `tokio` to 1.0

### ISSUE THREAD

**Issue by stanislav-tkach** [awslabs/aws-lambda-rust-runtime#278]
Many crates (including rusoto) have already been migrated to the 1.0 version. It would be nice to update the runtime, too.

**Comment by seanpianka** [comment]
There's an active fork of this project, maintained [here](https://github.com/lamedh-dev/aws-lambda-rust-runtime), which has already merged updates to Tokio 1.0, along with numerous other improvements contributed by the community. These same contributions have been blocked for months as PRs-awaiting-review in this project, so I recommend to migrate there.

Here's how I seamlessly replaced this version with the new fork in my `Cargo.toml`:
```toml
lambda_http = { package = "netlify_lambda_http", version = "0.2.0" }
```
