### ISSUE TITLE
How to Deploy: Docker asking for permissions

### ISSUE THREAD

**Issue by migeruj** [awslabs/aws-lambda-rust-runtime#279]
Hi guys! I'm trying to deploy the lambda_handler example with firstName in the body. But I'm getting this error trying to deploy with serverless framework.

I can't find anything related to the error, I would think it's from the docker that the framework uses.

```bash
0.2.7-rust-1.43.1: Pulling from softprops/lambda-rust
a981bd693b45: Pull complete
5059a57d636a: Pull complete
aa92f5809fd4: Pull complete
b9a6cbdc01eb: Pull complete
71882866df94: Pull complete
64266edabab8: Pull complete
3c1a14b26bb2: Pull complete
Digest: sha256:f106e6ab62e34e8cd0a4b310bc663dd03db04b2d34d3e2ac2e6c739fa21c4bc5
Status: Downloaded newer image for softprops/lambda-rust:0.2.7-rust-1.43.1
    Updating git repository `https://github.com/awslabs/aws-lambda-rust-runtime/`
warning: spurious network error (2 tries remaining): failed to mmap. Could not write data: Permission denied; class=Os (2)
warning: spurious network error (1 tries remaining): failed to mmap. Could not write data: Permission denied; class=Os (2)
error: failed to get `lambda` as a dependency of package `hello v0.1.0 (/code)`

Caused by:
  failed to load source for dependency `lambda`

Caused by:
  Unable to update https://github.com/awslabs/aws-lambda-rust-runtime/#c8dbcd39

Caused by:
  failed to fetch into /root/.cargo/git/db/aws-lambda-rust-runtime-7c865cce90132439

Caused by:
  failed to mmap. Could not write data: Permission denied; class=Os (2)
Serverless: Rust build encountered an error: undefined 1.

  Error --------------------------------------------------
```

My Environment

Rust version 1.43 Nightly
target=x86_64-unknown-linux-musl

![image](https://user-images.githubusercontent.com/26949232/105568237-e4d02d00-5d05-11eb-88b7-33df950177b9.png)

**Comment by johansmitsnl** [comment]
I'm using it with `dockerless: true` enabled on my Linux machine. For more information see https://www.serverless.com/plugins/serverless-rust

Can't see on which host system your running but it might solve your issue.

**Comment by migeruj** [comment]
Now I have taken up my project again. I changed the 'dockerless' parameter to true. Everything works without problems and I can now run rust on lambda with the serverless framework. Thanks!
