### ISSUE TITLE
Questions on Deployment and AL2

### ISSUE THREAD

**Issue by houstdav000** [awslabs/aws-lambda-rust-runtime#290]
So after a few weeks of confusion on this, I have to ask:

Do we _really_ target stable-x86_64-unknown-linux-muslc?

Because Amazon Linux 2 (AL2) [has glibc](https://aws.amazon.com/amazon-linux-2/faqs/) and even the Docker container used in the Docker Deployment section uses glibc, and does not target muslc (and targets AL2).

Is this a difference between the selection for "Custom Runtime" vs "Custom Runtime for Amazon Linux 2"?

If so, should the README be updated so that the AWS CLI instructions target AL2 to be consistent, or at least clarify the toolchain target step as needed only for the default Custom Runtime set?

**Comment by rimutaka** [comment]
We should update ReadMe with a note about AL1/musl vs AL2/glibc as per @davidbarsky explanation in https://github.com/awslabs/aws-lambda-rust-runtime/discussions/306#discussioncomment-485478

**Comment by coltonweaver** [comment]
Agreed, lets use this issue to track that work.

**Comment by rimutaka** [comment]
Can someone with iOS knowledge help me rephrase this part? I should be able to make the rest of the changes.

  * **Note:** If you are running on Mac OS you'll need to install the linker for the target platform. You do this using the `musl-cross` tap from [Homebrew](https://brew.sh/) which provides a complete cross-compilation toolchain for Mac OS. Once `musl-cross` is installed we will also need to inform cargo of the newly installed linker when building for the `x86_64-unknown-linux-musl` platform.
```bash
$ brew install filosottile/musl-cross/musl-cross
$ mkdir .cargo
$ echo $'[target.x86_64-unknown-linux-musl]\nlinker = "x86_64-linux-musl-gcc"' > .cargo/config
```

**Comment by nmoutschen** [comment]
I see the documentation has been updated since then, so I'll close this ticket. If you feel that something is missing here, feel free to reopen it or open a new one!
