### ISSUE TITLE
Not found link in the README about [basic example]

### ISSUE THREAD

**Issue by overheat** [awslabs/aws-lambda-rust-runtime#291]
Looks the URL link in the README for [basic example](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda/examples/hello-without-macro.rs) is not found.

**Comment by bahildebrand** [comment]
Good catch, I'll update the link.

**Comment by coltonweaver** [comment]
@bahildebrand When you take care of this can you remove the `type Error = Box<dyn std::error::Error + Send + Sync + 'static>;` that I forgot to remove from the README.md in #298?
