### ISSUE TITLE
0.3 Release

### ISSUE THREAD

**Issue by bahildebrand** [awslabs/aws-lambda-rust-runtime#294]
We are currently working towards a 0.3 release for the runtime! There are a few minor changes that need to be made for release, but most of the work is complete. This issue is mostly for tracking the release work that needs to be done. 

Please comment here if there are major issues you think should make it into the release.

**Comment by bahildebrand** [comment]
Made some minor changes, but otherwise I think it looks good.

**Comment by miere** [comment]
That’s great news! Is it possible to include one extra tweak in the current lambda-runtime?

I really believe it would be beneficial if we remove the requirement to rewrite our own [Error alias](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-runtime/examples/error-handling.rs#L10) for each lambda endpoint. By simply making the [existing one](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-runtime/src/lib.rs#L34) public would solve this problem. It would also allow the maintainers to create their own backward compatible Error type, with little to (possibly) zero impact on users of this library.

**Comment by bahildebrand** [comment]
> 
> 
> Hey guys, that's awesome we've been waiting for it a lot (cc #274). Could you elaborate on what has changed with the maintainership of this repo? Am I right that AWS is dedicating some resources for this repo's support?

@coltonweaver and I are both maintaining the repo in our free time. Neither of us are on the Lambda team.

> 
> 
> That’s great news! Is it possible to include one extra tweak in the current lambda-runtime?
> 
> I really believe it would be beneficial if we remove the requirement to rewrite our own [Error alias](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-runtime/examples/error-handling.rs#L10) for each lambda endpoint. By simply making the [existing one](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-runtime/src/lib.rs#L34) public would solve this problem. It would also allow the maintainers to create their own backward compatible Error type, with little to (possibly) zero impact on users of this library.

This seems like a reasonable request to me. Would you mind opening an issue, and I can take a look tomorrow?

**Comment by henriiik** [comment]
> @coltonweaver and I are both maintaining the repo in our free time. Neither of us are on the Lambda team.
@bahildebrand thank you for taking the time to do it! ❤

**Comment by brainstorm** [comment]
> > @coltonweaver and I are both maintaining the repo in our free time. Neither of us are on the Lambda team.
> 
> @bahildebrand thank you for taking the time to do it! ❤

I second that, looking forward to this release to reboot my project built on top of this lib, kudos! :_)

**Comment by bahildebrand** [comment]
[lambda_runtime](https://crates.io/crates/lambda_runtime) and [lambda_http](https://crates.io/crates/lambda_http) are both at 0.3.0 on crates.io! The docs are currently in the [build queue](https://docs.rs/releases/queue) for docs.rs.
