### ISSUE TITLE
Gitpage page not found?

### ISSUE THREAD

**Issue by awsa2ron** [awslabs/aws-lambda-rust-runtime#300]
I clicked on the gitpage link in [code page](https://github.com/awslabs/aws-lambda-rust-runtime), and the "deployment" button. Page not found.

**Comment by coltonweaver** [comment]
Nice catch. Something was missed during some refactoring that we did. Addressed that here: https://github.com/awslabs/aws-lambda-rust-runtime/pull/303

**Comment by coltonweaver** [comment]
This should be fixed now, going to close this.
