### ISSUE TITLE
How could I send a MQTT message to aws iot core in the lambda.

### ISSUE THREAD

**Issue by awsa2ron** [awslabs/aws-lambda-rust-runtime#304]
How to publish a MQTT message to aws iot core by using this package?
lambda-mqtt or similar example?

Thanks!

**Comment by johann2** [comment]
This crate only provides the base functionality for running Rust code on AWS Lambda.
To publish MQTT messages, I'd recomend the `rumqttc` crate instead. AWS iot also supports publishing messages over HTTPS, which could be a better fit for your purposes.

**Comment by bahildebrand** [comment]
As @johann2 mentioned this is really outside of the scope of this crate. Assuming you're trying to update a device shadow in iot you could use [request](https://github.com/seanmonstar/reqwest) or [hyper](https://github.com/hyperium/hyper) to send an update to the [device shadow REST API](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-rest-api.html), or you could use [mqtt-rs](https://github.com/zonyitoo/mqtt-rs) to send to a [device shadow topic](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-mqtt.html).

**Comment by awsa2ron** [comment]
> As @johann2 mentioned this is really outside of the scope of this crate. Assuming you're trying to update a device shadow in iot you could use [reqwest](https://github.com/seanmonstar/reqwest) or [hyper](https://github.com/hyperium/hyper) to send an update to the [device shadow REST API](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-rest-api.html), or you could use [mqtt-rs](https://github.com/zonyitoo/mqtt-rs) to send to a [device shadow topic](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-mqtt.html).

Good hints!

BTW, this doc [Using AWS Lambda with other services](https://docs.aws.amazon.com/lambda/latest/dg/services-iot.html), looks it is very important feature for lambda to work with other aws services.
Do you think need to creating another crate to support such kind of work with other aws services feature?

**Comment by bahildebrand** [comment]
Interacting with other services is usually fairly opaque from the lambda code perspective. Using the example of triggering from AWS IOT, if you used [AWS IOT SQL](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sql-reference.html) to trigger a lambda on some sensor value you would just receive whatever JSON message was sent from the select statement. From your Lambda code's perspective it has no knowledge of the service that called it.

The only exception to this is invocations from API gateway, and ALB which have some extra work that needs to be done. That is why the lambda_http crate is present, so that no custom logic needs to be used for those cases.

**Comment by awsa2ron** [comment]
@bahildebrand 
> Interacting with other services is usually fairly opaque from the lambda code perspective. Using the example of triggering from AWS IOT, if you used [AWS IOT SQL](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sql-reference.html) to trigger a lambda on some sensor value you would just receive whatever JSON message was sent from the select statement. 
> 

Yes, I am using the aws IoT rule engin to trigger lambda and I received JSON message.

Actually I want to reply MQTT message to that device which trigger the lambda if I know the MQTT topic that device have subcribed.  Any hints?

Thanks!

**Comment by awsa2ron** [comment]
What I am looking for is the rust version of this code(Python):
```
import boto3
import json

client = boto3.client('iot-data', region_name='eu-west-1')

pay = 'hello2'

def lambda_handler(event, context):
    response = client.publish(
        topic='mytopic/iot',
        qos=1,
        payload=pay
    )
```

**Comment by voteblake** [comment]
@awsa2ron There is a set of crates available called [`rusoto`](https://crates.io/crates/rusoto_core) which expose Rust interfaces for AWS API's similar to what the `boto3` libraries provide in Python. They do have an `IotData` client that provides a [`publish`](https://rusoto.github.io/rusoto/rusoto_iot_data/trait.IotData.html#tymethod.publish) method. It looks like you would want to bring that in as a dependency for your Lambda function, then call it within the handler.

**Comment by bahildebrand** [comment]
@voteblake looks like he's given you the answer to your root question. Are you comfortable closing this @awsa2ron ?

**Comment by awsa2ron** [comment]
@bahildebrand Sure!
Thanks.
