### ISSUE TITLE
LambdaRequest seems to missing `resource` field

### ISSUE THREAD

**Issue by MathiasKoch** [awslabs/aws-lambda-rust-runtime#307]
https://github.com/awslabs/aws-lambda-rust-runtime/blob/d3ff4352c4b0e64fb46af2ca425db39211237e26/lambda-http/src/request.rs#L70-L89

Seems to be missing a `resource` field?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/682a17a7683c34d23d6f70416f21e7f65671885c/types/aws-lambda/trigger/api-gateway-proxy.d.ts#L89-L102

This causes my event to fail serializing, rendering the entire lambda-http crate useless?

**Comment by MathiasKoch** [comment]
It also seems like `ApiGatewayRequestContext` is missing a few fields, as per the document linked in the code: See [context-variable-reference](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html) for more detail.

**Comment by bahildebrand** [comment]
Agreed this looks like an issue. Would you mind creating a toy example to recreate your issue, and I can take a look at it?

**Comment by duaneking** [comment]
This is blocking basic functionality for many calls.  Is somebody already working on this? Is there a fix planned? This makes this library unusable.
