### ISSUE TITLE
Failing to create Context when running within al2.provided container

### ISSUE THREAD

**Issue by twhit0611** [awslabs/aws-lambda-rust-runtime#313]
When running the aws-lambda-rust-runtime (v0.3.x) in the official AWS Lambda container image (public.ecr.aws/lambda/provided:al2) , the runtime panics due to missing headers. We attempted to send the headers in the request but they do not seem to make it into TryFrom trait implementation for the context struct when running in a local Docker environment.

In order to make the runtime easier to consume, we would like to introduce a reasonable set of default values for the AWS Context to be used in combination with the official AWS Lambda container image. The values we chose came directly from the [official AWS documentation](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html) for Lambda context.

**Comment by bahildebrand** [comment]
This is a problem caused upstream, and doesn't make sense to fix in the runtime. See the discussion in #314 for more info.
