### ISSUE TITLE
Receiving binary/base64 request

### ISSUE THREAD

**Issue by RedHatter** [awslabs/aws-lambda-rust-runtime#320]
I would like to write a lambda that processes a binary request. After adding my mime type to binaryMediaTypes the API Gateway sends a base64 encoded body but lambda_runtime is unable to parse it.
```
{
    "Type": "User",
    "message": "Could not parse request body into json: Could not parse payload into json: Unrecognized token 'FQAAAAAAAAAmC3owgQFRqkTRQ34DL5Z': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (byte[])\"FQAAAAAAAAAmC3owgQFRqkTRQ34DL5Z/YglgcwBAAAAAAAAAAAzXMZSwObEMep6gVimhaqjvuFyL1JT9EOrmkO58uta08lfxMny6RrK/RndB4qvr0mRAY0D6ZBK7twXX0WO4OQkgAAAAAAAAADLMv8gkCBIHVBpYE7RA18XPVVCvKx/NJWDvtgH6qdkfCAAAAAAAAADrQ+FBi5emKA==\"; line: 1, column: 33]"
}
```
Is there any way I can get lambda_runtime to pass me the raw body without attempting to parse it as JSON?

**Comment by tysg** [comment]
Try the lambda_http crate which gives you more fine-grained control over the request body.

**Comment by calavera** [comment]
closing this issue because lambda_http can do that for you.
