### ISSUE TITLE
Error building the hello-world project

### ISSUE THREAD

**Issue by mnishizawa** [awslabs/aws-lambda-rust-runtime#328]
I am following the instructions on the readme at https://github.com/awslabs/aws-lambda-rust-runtime

When I get  to the build step, it fails because log and simple_logger are specified as dev dependencies.  Moving them to the regular dependencies in the Cargo.toml file and rebuilding succeeds. Not sure if this is an error with the code or an error with the documentation, but it does not work as documented.

**Comment by nirLumigo** [comment]
I got the same error:
```
7 | use simple_logger::SimpleLogger;
  |     ^^^^^^^^^^^^^ use of undeclared crate or module `simple_logger`
```

**Comment by duaneking** [comment]
As of right now, that does not even work.  None of the examples seem to build or compile in latest standard rust.  Is this crate unmaintained?  Nothing is working.

**Comment by calavera** [comment]
This should be fixed now. The examples have been updated to not use simple_logger, and the instructions in the readme are more clear: https://github.com/awslabs/aws-lambda-rust-runtime#aws-cli
