### ISSUE TITLE
Add either an example or actual dispatch based on handler name

### ISSUE THREAD

**Issue by nakedible-p** [awslabs/aws-lambda-rust-runtime#329]
It is customary to be able to use the same Lambda function for many different purposes by giving a separate "handler name". For Node.js and Python, this directly affects the name of the function that is invoked as the entry point to process the event.

You seem to totally ignore this handler name, as evidenced by your example to creating a function:
```
  --handler doesnt.matter \
```

The execution environments are not shared between different "handler name" values, as they must be separate AWS Lambda functions anyway, with possibly differing memory amounts, roles, etc. This means that the "handler name" is already known when starting the runtime, and will not change for the lifetime of the runtime.

I haven't tested this, but I think it is provided in the environment variable `_HANDLER`, which would mean that it should be trivial to support this:

```rust
#[tokio::main]
async fn main() -> Result<(), Error> {
    let func = handler_fn(match std::env::var("_HANDLER")? {
        "a" => func_a,
        "b" => func_b,
    });
    lambda_runtime::run(func).await?;
    Ok(())
}
```

Some functionality for automatically handling this dispatch could possibly be added - or if the above example is trivial enough of a way to handle it, then there probably should be an example file explaining that this is the way to do "multiple entrypoint" functions with this.

**Comment by rimutaka** [comment]
What would be the use case for this? It kind of goes against the grain of what Rust is about. Not saying it's a bad idea, just don't see a practical application where this approach would be beneficial.

**Comment by calavera** [comment]
> don't see a practical application where this approach would be beneficial.

I agree with this. 

You can also do that dispatch yourself by setting any environment variable that you want, you don't need to rely on the handler's name.

Example:

```rust
#[tokio::main]
async fn main() -> Result<(), Error> {
    let func = handler_fn(match std::env::var("CHOOSE_HANDLER_BASED_ON_MY_ENVIRONMENT_VAR")? {
        "a" => func_a,
        "b" => func_b,
    });
    lambda_runtime::run(func).await?;
    Ok(())
}
```

In fact, the handler's name is mostly an internal implementation detail. The Go runtime doesn't rely on that name, and I have a gut feeling that lambda containers don't care about it either.

I'm going to close this issue because I don't think it's something to act upon. Feel free to reopen if we should strongly reconsider it.

**Comment by nakedible-p** [comment]
I was really busy, so forgot all about answering this. It doesn't really matter to me if this is mentioned in the docs or not, but I'll make the case here nevertheless.

There are many cases where the functionality of Lambda depends on a big library which provides many separate but related functions.

One can build a separate binary and Lambda zip for every different function, but if the binaries are large (containing something like phantomjs perhaps), then there's a lot of large zip files to lug around so it's not the ideal choice. It also easily results in a bunch of boilerplate code for the different binaries.

One can simply switch functionality inside the Lambda based on the payload received, if the payloads are distinct, but that means that all the separate use cases need to share the same IAM policy, memory, timeout, etc. which is often not the case. 

One can switch based on a custom environment variable, which solves all the problems, but why do it when there's a separate field in Lambda configuration especially intended for this purpose: the handler name. Also, Lambda@Edge does not support environment variables.

I don't understand why any of this would go against the grain of Rust in any way, or why it would be needed less with Rust than with other languages.

In practical matters, since Lambda will never share the same environment for multiple functions, the handler name should be available at function startup. Hence I think this will be enough for the functionality I am talking about:

```rust
    let handler = std::env::var("_HANDLER")?;
    match handler.as_str() {
        "AuthorizeDebit" => run(service_fn(authorize_debit_handler)).await,
        "Test" => run(service_fn(function_handler)).await,
        _ => panic!("unknown handler name"),
    }
```

@calavera
