### ISSUE TITLE
Not possible to create a Context for testing

### ISSUE THREAD

**Issue by leepa** [awslabs/aws-lambda-rust-runtime#33]
I would like to create a mock Context to be able to test my handler fully. Unfortunately deadline is private and new requires a config provider and the ConfigProvider is in env, which is private.

Any pointers?

**Comment by davidbarsky** [comment]
Uh, we should probably make those public. That’s my suggestion 😬

**Comment by leepa** [comment]
Pretty pretty please - It'd make testing a lot easier. They are public in the Java libs.
