### ISSUE TITLE
Does lambda_http::Handler::Future requires Send ?

### ISSUE THREAD

**Issue by fmonniot** [awslabs/aws-lambda-rust-runtime#342]
Hello there,

The current implementation of `lambda_http`'s [`Handler::Fut`](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-http/src/lib.rs#L97) requires a `Send` bound, but the underlying `lambda_runtime`'s [`Handler::Fut`](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-runtime/src/lib.rs#L76) does not. Is there a reason why this bound is present? Future-proofing the API or remnant of the past perhaps? The crate still compiles (and the tests pass) after removing the bound.

Would the team be interesting in a PR with [this commit](https://github.com/fmonniot/aws-lambda-rust-runtime/commit/5737b61b818617bb1fba0636ad749687c9c528b7).

This open up some interesting avenue too. For example, I found this issue while trying to integrate actix on top of the `lambda_http` crate (swaping out `HttpServer` with `lambda_runtime::run(lambda_http::handler` basically).

Thanks !

**Comment by coltonweaver** [comment]
Hi @fmonniot, thanks for pointing this out! This is indeed unintentional. I missed this change whenever I made the changes to remove the `'static` bounds from `lambda_http` to match the runtime. If you want to go ahead and publish your linked commit as a PR, I would happily review it.

**Comment by fmonniot** [comment]
No worry and thanks for the prompt response. I opened #344 with the change.

**Comment by coltonweaver** [comment]
Just approved and merged your code in. Thanks for making this change! Feel free to reopen this issue if needed.

**Comment by singularsyntax** [comment]
Has there been a regression on this? Or a decision to reverse course and again require `Send`?

Using

    lambda_http = "0.16.0"

and this code

```
use std::{cell::RefCell, sync::RwLock};
use lambda_http::{service_fn, Body, Error, Request, Response};
use log::debug;

#[derive(Debug)]
struct ServerContext {
    _something: RefCell<()>    
}

async fn handler(server_ctx: &ServerContext, request: Request) -> Result<Response<Body>, Error> {
    debug!("server_ctx: {:?}, request: {:?}", server_ctx, request);

    let response = Response::builder()
        .status(200)
        .header("Content-Type", "text/plain")
        .body("Hello World!".into())
        .map_err(Box::new)?;

    Ok(response)
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    let server_ctx = ServerContext { _something: RefCell::new(()) };
    lambda_http::run(service_fn(|request| async { handler(&server_ctx, request).await })).await
}
```

I get this error:

```
error[E0277]: `RefCell<()>` cannot be shared between threads safely
   --> src/main.rs:35:22
    |
35  |     lambda_http::run(service_fn(|request| async { handler(&server_ctx, request).await })).await
    |     ---------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `RefCell<()>` cannot be shared between threads safely
    |     |
    |     required by a bound introduced by this call
    |
    = help: within `ServerContext`, the trait `Sync` is not implemented for `RefCell<()>`, which is required by `{async block@src/main.rs:35:43: 35:48}: Send`
    = note: if you want to do aliasing and mutation between multiple threads, use `std::sync::RwLock` instead
note: required because it appears within the type `ServerContext`
   --> src/main.rs:6:8
    |
6   | struct ServerContext {
    |        ^^^^^^^^^^^^^
    = note: required for `&ServerContext` to implement `Send`
note: required because it's used within this `async` block
   --> src/main.rs:35:43
    |
35  |     lambda_http::run(service_fn(|request| async { handler(&server_ctx, request).await })).await
    |                                           ^^^^^
note: required by a bound in `lambda_http::run`
   --> /Users/sscheck/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lambda_http-0.16.0/src/lib.rs:197:16
    |
194 | pub async fn run<'a, R, S, E>(handler: S) -> Result<(), Error>
    |              --- required by a bound in this function
...
197 |     S::Future: Send + 'a,
    |                ^^^^ required by this bound in `run`

For more information about this error, try `rustc --explain E0277`.
```

Sure enough, if I follow the compiler's advice and replace `std::cell::RefCell` with `std::sync::RwLock`, it compiles.

Am I missing something here?
