### ISSUE TITLE
Fix link to the prepared Docker images with Rust for Lambda

### ISSUE THREAD

**Issue by zamazan4ik** [awslabs/aws-lambda-rust-runtime#346]
Hi!

I want to propose a slight change to the README file. You reference the https://github.com/softprops/lambda-rust repo as a repo with `lambda-rust` Docker images. Unfortunately, this repo is in an unmaintained-like state (see https://github.com/softprops/lambda-rust/issues/99).

We (me and other people) created a new org, where we've continued preparing related Docker images for newer Rust versions - https://github.com/rust-serverless/lambda-rust

So I suggest at least add a note about the new place where people can grab Docker images for newer Rust versions.

Also, will be awesome, if such a useful thing like Docker images, will be a part for awslabs organization, so they always will be in a maintained state (I hope). And a chance of yet another transition will be reduced. What do you think?

Thanks!

**Comment by ytitov** [comment]
Thank you for the updated repo.  It finally worked for me. @ZaMaZaN4iK
