### ISSUE TITLE
Lets encrypt certificate expired issue

### ISSUE THREAD

**Issue by dekanayake** [awslabs/aws-lambda-rust-runtime#351]
hi, I'm using rust lambda for one of my production systems. I have a client service that calls HTTPS REST API. It was working without any issues, but today suddenly it started to fail with the following error.

error sending request for url (https://xx.xx.com/api/f43b0181-6ee9-4539-b3e9-f7f37a95f962/delivery/v1/search?q=(number1:650): error trying to connect: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1264: (certificate has expired) . I think this is failing due to the lets encrypt DST Root CA X3 root certificate expiery.

I tried to fix this issue by attaching the root certificate Signed by ISRG Root X1 to reqwest client builder no luck. Could you please help me to fix this issue? Thanks.

**Comment by nmoutschen** [comment]
Hi @dekanayake !

The issue should've been resolved on the Lambda side by now, but just to look into this deeper: how did you pass the root CA to reqwest's client builder? You should be able to use [`add_root_certificate`](https://docs.rs/reqwest/0.11.6/reqwest/struct.ClientBuilder.html#method.add_root_certificate) on the builder to add the certificate. Have you also tried by [disabling the built-in certs](https://docs.rs/reqwest/0.11.6/reqwest/struct.ClientBuilder.html#method.tls_built_in_root_certs) to see if they caused any interference?

**Comment by coltonweaver** [comment]
@dekanayake I'm going to close this issue because I believe this should have been resolved on the Lambda side now as @nmoutschen mentioned. Please feel free to reopen if you're still having issues!
