### ISSUE TITLE
Upgrade tracing-subscriber to fix RUSTSEC advisory

### ISSUE THREAD

**Issue by seanpianka** [awslabs/aws-lambda-rust-runtime#357]
[tracing-subscriber 0.3.0](https://github.com/tokio-rs/tracing/releases/tag/tracing-subscriber-0.3.0) was released 3 days ago in order to fix  [RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159.html). As `aws-lambda-rust-runtime` has a 0.2 dependency, it would be best if this dependency was updated to 0.3 to avoid usage of `chrono`  and support new `tracing-*` releases.

**Comment by coltonweaver** [comment]
Closing this after merging the related PR.
