### ISSUE TITLE
fork/exec /var/task/bootstrap: no such file or directory

### ISSUE THREAD

**Issue by khryte** [awslabs/aws-lambda-rust-runtime#361]
I get this error no matter what program I compile:

```text
Error: fork/exec /var/task/bootstrap: no such file or directory
Runtime.InvalidEntrypoint
```

It doesn't matter if I compile with or without the Docker image, so I will show the docker image I've been using so far:

```Dockerfile
FROM rust:latest
RUN rustup target add x86_64-unknown-linux-musl
RUN apt update && apt install -y musl-tools
RUN rm -rf /var/lib/apt/lists/* /var/cache/apt/*
```

Here's the script I've been using to build:

```bash
#!/usr/bin/env bash

LAMBDA_ARCH="linux/amd64"
RUST_TARGET="x86_64-unknown-linux-musl"

docker run \
  --platform ${LAMBDA_ARCH} \
  --rm --user "$(id -u)":"$(id -g)" \
  -v "${PWD}":/usr/src/myapp -w /usr/src/myapp rustbuilder:latest \
  cargo build -p my_binary --release --target ${RUST_TARGET}

rm "lambda.zip"
zip -j "lambda.zip" "target/${RUST_TARGET}/release/bootstrap"
```

The programs can be anything. The trivial example in this repository yields the same error. Interestingly enough, it *does* work if I use Rust 1.45.2, but this is unfortunately not an option for me, since it can't compile some of the libraries I rely on in production.

I'm very grateful for any help, I've been bashing my head against this for a couple of days now.

Edit:
I've tried a lot of different Rust versions now, and it seems that 1.45.2 is the last version I'm able to use. Using 1.46 and everything thereafter results in a broken binary.

**Comment by coltonweaver** [comment]
Hey! Can you tell me a little bit about the setup you're using to compile?

If you're using x86_64-unknown-linux-musl, have you tried using `provided.al` instead of `al2`? I recall there being an issue with musl-produced binaries running on `al2` that I think you're seeing.

**Comment by segfaultsourcery** [comment]
Hi! Thanks for the response. I've tried using `x86_64-unknown-linux-gnu` earlier, which results in error messages similar to this: `/lib64/libc.so.6: version `GLIBC_2.18' not found`. 

Could you elaborate a little bit on how to use `provided.al`? I'm not sure what it is.

**Comment by khryte** [comment]
Hi! Thanks for the response. I've tried using x86_64-unknown-linux-gnu earlier, which results in error messages similar to this: /lib64/libc.so.6: version GLIBC_2.18' not found`.

Could you elaborate a little bit on how to use provided.al? I'm not sure what it is.

**Comment by coltonweaver** [comment]
Hmmm that's interesting. `/lib64/libc.so.6: version GLIBC_2.18 not found` would indicate that the image you're using to build doesn't have new enough binaries to produce the `-gnu` executable. 

Are you able to use another image to test? Can you try using the official Rust docker image?

**Comment by coltonweaver** [comment]
Apologies, just realized that's what rustbuilder is in this case! Let me take a deeper look at this. Have you considered updating GLIBC in the image?

**Comment by khryte** [comment]
No worries at all! Updating GLIBC to the latest version does indeed work (when I compile with `x86_64-unknown-linux-gnu` rather than `-musl`), but I'm worried that an AL/AL2 upgrade might break production. Can I assume that the version will stay the same indefinitely?

**Comment by khryte** [comment]
...okay, now, for some reason, the `-gnu` builds are failing again. The glibc version in the builder image is this:

```bash
# apt-cache madison libc6
     libc6 | 2.31-13+deb11u2 | http://deb.debian.org/debian bullseye/main amd64 Packages
```

Running the lambda results in this error again:

```json
{
  "errorMessage": "RequestId: deb03851-9e5d-48ca-9327-18f0728bca4c Error: Runtime exited with error: exit status 1",
  "errorType": "Runtime.ExitError"
}
```

```
START RequestId: deb03851-9e5d-48ca-9327-18f0728bca4c Version: $LATEST
/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /var/task/bootstrap)
END RequestId: deb03851-9e5d-48ca-9327-18f0728bca4c
```
