### ISSUE TITLE
Allow for modifying the incoming lambda event prior to deserialization

### ISSUE THREAD

**Issue by dustbort** [awslabs/aws-lambda-rust-runtime#362]
I am using [localstack](https://github.com/localstack/localstack) to test lambda functions written using this runtime. I have found in [some cases](https://github.com/LegNeato/aws-lambda-events/issues/47) that the structs defined in [aws-lambda-event](https://github.com/LegNeato/aws-lambda-events/issues/47) do not match the events generated in localstack in some minor ways. aws-lambda-events also has some past cases of mismatched optional fields, due to how the Rust structs were generated from Go code. So this sort of thing can happen for multiple reasons.

When the struct mismatches in any way, such as an omitted field not being optional, the entire deserialization fails, and I am stuck.
```
Error: data did not match any variant of untagged enum LambdaRequest
```
Then I will have to approach localstack and/or aws-lambda-events and try to get the mismatch resolved. This seems like a potentially ongoing issue, based on past Github issues and the strictness of the deserialization.

Rather than expecting the incoming event to match 100%, which seems fairly brittle given that many of the fields may be irrelevant for my application, one way to work around this would be to allow me to modify the incoming event before it is deserialized. This way, I could patch the minor mismatched structures.  For example, [on this line](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-runtime/src/lib.rs#L159), allowing a custom function as opposed to using serde_json directly.

I have not found an existing point to inject this behavior, and I have looked for where I can implement it will the minimum amount of code duplication, but because a number of depended-upon structs are not exported, such as [Client](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-runtime/src/client.rs#L7), I would have to duplicate nearly the entire crate to achieve this behavior.

I am requesting that the runtime allow for this custom deserialization behavior to be injected easily, to avoid potentially ongoing issues of fragility with deserialization.

**Comment by nmoutschen** [comment]
Hey @dustbort !

Thanks for opening this issue! I did a quick test and you could run your own logic to transform a JSON value into a valid event in the invocation loop itself:

```rust
use lambda_runtime::{handler_fn, Context, Error};
use crate::MyType;

#[tokio::main]
async fn main() -> Result<(), Error> {
    lambda_runtime::run(handler_fn(my_lambda_handler)).await?;

    Ok(())
}

// The handler can take a serde_json::Value as input,
// any type is valid as long as it implements Deserialize.
async fn my_lambda_handler(event: serde_json::Value, _: Context) -> Result<(), Error> {
    // Add transformation logic here

    // Transform into an object
    let my_value:MyType = serde_json::value::from_value(event)?;

    println!("{:?}", my_value);

    Ok(())
}
```

Would that work for your use-case?

**Comment by dustbort** [comment]
Yes, that works a treat. Thank so much!
