### ISSUE TITLE
Using stable for cargo fmt in GitHub actions

### ISSUE THREAD

**Issue by nmoutschen** [awslabs/aws-lambda-rust-runtime#380]
Hey folks! 👋 

I've noticed this uses the nightly version of Rust to do `fmt` and `clippy` checks (see https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/.github/workflows/build.yml#L60-L81).

Since those versions might include new checks that are not yet in stable, and most people are using stable, should we change to using stable there too?

**Comment by coltonweaver** [comment]
I think we should 100% use stable. Good call out.

**Comment by nmoutschen** [comment]
Actually, looking at the bigger picture, we should probably define an MSRV at some point too.

I'll do some tests to see what we could realistically support.  In the crate's current stage, we could lower MSRV to 1.46.0 with three small changes:

* Downgrade edition for `lambda-extension` and `lambda-runtime-api-client` to 2018; and
* Import `std::convert::TryInto` for `lambda-runtime-api-client`.

We can't go any lower that this due to [while and if usage in `const fn`](https://github.com/rust-lang/rust/issues/49146) in `http-0.2.5`.

Counter argument to this is that aligning with the Rust SDK will probably be good enough. We'd still need to make those changes to support `1.53.0` too.

I can make those changes tomorrow and submit a PR.

**Comment by bahildebrand** [comment]
@nmoutschen can we close this? I see a related PR is merged, but not sure if there is any work remaining.

**Comment by nmoutschen** [comment]
Yes we can! :)
