### ISSUE TITLE
Implementation of `http_body::Body` for `lambda_http::Body`

### ISSUE THREAD

**Issue by oddg** [awslabs/aws-lambda-rust-runtime#398]
Hello,

I am wondering if implementing the [`http_body::Body` trait](https://docs.rs/http-body/latest/http_body/trait.Body.html) is on the road map for the [`lambda_http::Body` enum](https://docs.rs/lambda_http/latest/lambda_http/enum.Body.html).

This would improve interoperability with other libraries.

**Comment by calavera** [comment]
I don't think anyone thought about it before, but it sounds like a neat idea. Feel free to submit a pull request.
