### ISSUE TITLE
[RFC] Wrap interface for `tower::Service<Request>`

### ISSUE THREAD

**Issue by nmoutschen** [awslabs/aws-lambda-rust-runtime#404]
__Remark__: This is a follow-up to https://github.com/awslabs/aws-lambda-rust-runtime/issues/374 as I'm currently implementing it. See https://github.com/awslabs/aws-lambda-rust-runtime/pull/401 for progress.

## Background

Right now, the current implementation in `lambda_http::handler` takes a handler function that takes a `Request` and returns an `IntoResponse` implementation. This allows to pass the wrapped handler function into `lambda_runtime::run` directly. However, it has a few limitations.

First, `Request` and `IntoResponse` aren't `Deserialize` and `Serialize`, but `lambda_runtime::run` require those traits. It means we have to pass through an intermediate `Adapter` to transform the requests and responses. This is currently handled by [`lambda_http::handler`](https://docs.rs/lambda_http/0.4.1/lambda_http/fn.handler.html). As a consequence, the current implementation doesn't allow taking a `lambda_runtime::Handler` implementation directly. It offers a [`lambda_http::Handler`](https://docs.rs/lambda_http/0.4.1/lambda_http/trait.Handler.html), which implements it.

This causes some switching away from custom `Handler` traits towards `tower::Service`. Ideally, we should allow users to provide `tower::Service<Request>` implementations, and handle the transformation under the hood on their behalf. However, due to `lambda_runtime::run`'s signature, we cannot do that as-is. We also cannot implement `Deserialize` and `Serialize` for `Request` and `Response`, as those are all [foreign traits and types](https://doc.rust-lang.org/error-index.html#E0117).

## Proposition 1: extension trait for `Service<Request>`

```rust
use tower::Service;
use lambda_http::{Request, ServiceExt};

#[derive(Default)]
struct MyHandler;

impl Service<Request> for MyHandler {
    // skipped
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    // Use .into_runtime() to transform the Service
    lambda_runtime::run(MyHandler::default().into_runtime()).await
}
```

## Proposition 2: create a `lambda_http::run` wrapper

```rust
use tower::Service;
use lambda_http::Request;

#[derive(Default)]
struct MyHandler;

impl Service<Request> for MyHandler {
    // skipped
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    // Use lambda_http::run to wrap the Service
    lambda_http::run(MyHandler::default()).await
}
```

## Proposition 3: your idea here

If you have an idea that gives a cleaner interface, let me know!

**Comment by brainstorm** [comment]
I do find Proposition 2 more clean than prop 1, as an end user that is.

**Comment by rimutaka** [comment]
What are the limitations of Prop 1 vs Prop 2? If the only difference is having `.into_runtime()` then Prop 2 seems nicer.

**Comment by calavera** [comment]
Option 2 looks more clear to me. I link that I don't have to remember a different crate name to run the service, it's all in `lambda_http`.

**Comment by greenwoodcm** [comment]
I agree that Prop 2 seems cleaner as well

**Comment by nmoutschen** [comment]
Looks like everyone's on agreement on this, and this will simplify the external interface quite a lot. 😄 Thanks, folks!

**Comment by LucioFranco** [comment]
I think prop 2 looks good. I would probably use `service_fn` over a manual service implementation. In addition, this supports people to use things like warp or axum which is nice. I think building around tower is a great initiative (I think ive wanted this in here for a while). 

cc @davidpdrsn may be interested

**Comment by davidpdrsn** [comment]
> I think building around tower is a great initiative (I think ive wanted this in here for a while). 

I agree! This looks great 😃

**Comment by coltonweaver** [comment]
+1 to seeing if we can use `service_fn`, but overall Prop 2 is great. Thanks for putting this together @nmoutschen!

**Comment by nmoutschen** [comment]
Closing the ticket as this is now implemented in https://github.com/awslabs/aws-lambda-rust-runtime/pull/401/commits/84d41c9ba069ca7d40d0ff156bb84e974db10f0d
