### ISSUE TITLE
lambda_http: Use http_body::Body for responses

### ISSUE THREAD

**Issue by nmoutschen** [awslabs/aws-lambda-rust-runtime#409]
Since https://github.com/awslabs/aws-lambda-rust-runtime/pull/406, `lambda_http::Body` implements `http_body::Body`. However, `lambda_http::LambdaResponse` only accepts `lambda_http::Body` as response body.

With this proposal, we could create a `LambdaResponse` from any `Request<http_body::Body>`, which means Lambda functions could return anything that implements this trait.

## Drawbacks

Right now, we support receiving a [`serde_json::Value`](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-http/src/response.rs#L201-L212) or other [values that implement `Into<Body>`](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-http/src/body.rs#L95-L143) because we use a custom type.

I think this would no longer be possible if we accept a foreign trait, or would involve a bit more complexities on the implementation side.

**Comment by bnusunny** [comment]
This will be very useful. For example, in [AWS Lambda Adapter](https://github.com/aws-samples/aws-lambda-adapter), I have to convert from reqwest::Response to lambda_http::LambdaResponse. If this conversion is handled by lambda-http, it will help to remove big chunck of code from Lambda Adapter.

**Comment by calavera** [comment]
> I think this would no longer be possible if we accept a foreign trait, or would involve a bit more complexities on the implementation side.

I think we need to see before/after examples of how this would work.

**Comment by bnusunny** [comment]
Yes, this was done in #491.
