### ISSUE TITLE
Migrate to Rust 2021 edition

### ISSUE THREAD

**Issue by calavera** [awslabs/aws-lambda-rust-runtime#414]
There were some issues migrating to 2021 edition. I think we should address the problems and move all the crates to the 2021 editions.

**Comment by nmoutschen** [comment]
Is there any compelling reason to move to 2021 at the moment?

Currently, the AWS SDK is on 2018 with a MSRV of 1.54.0, so I'd personally prefer to stay there for compatibility reason.

**Comment by brainstorm** [comment]
I don't seem to have any compat issues from the user side using latest versions of AWS SDK: https://github.com/umccr/s3-rust-noodles-bam/blob/master/Cargo.toml#L5

**Comment by brainstorm** [comment]
https://github.com/awslabs/smithy-rs/pull/1388
