### ISSUE TITLE
Change default branch to `main`

### ISSUE THREAD

**Issue by calavera** [awslabs/aws-lambda-rust-runtime#421]
That's the default branch name that we've been using in all our repositories. I believe we should make the update here sooner rather than later.

**Comment by nmoutschen** [comment]
Sounds good!

I think the most important changes will be on the GitHub workflows (e.g. [here](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/.github/workflows/build.yml#L87)), and we should keep the master branch for those that use it as a dependency, but we should definitively switch to `main`.
