### ISSUE TITLE
Request body helper method

### ISSUE THREAD

**Issue by ymwjbxxq** [awslabs/aws-lambda-rust-runtime#431]
Hello,

currently, I do this for each route that uses a body

```rust
pub async fn execute(event: Request) -> Result<impl IntoResponse, Error> {
    let body: Result<MyStruct, serde_json::Error> = match event.body() {
        Body::Text(body) => serde_json::from_str(body),
       Body::Binary(body) => serde_json::from_slice(body),
        _ => {
            return Ok(Response::builder()
                .status(StatusCode::BAD_REQUEST)
                .header("Content-Type", "application/json")
                .body(json!({"message": "Empty request body"}).to_string())
                .expect("failed to render response"));
        }
    };

    if let Ok(request) = body {
     // do something
  } else {
        // return failed to parse
  }

```

I think all of this could be hidden, and the SDK should expose some helper method that will return a Result but that it will take care of doing the transformation.

I would like to pass my struct, so my T and give the type of Body, and this helper method will return T if everything is okay or the type of Error.

I hope this is clear. I wish to remove the boilerplate code and leave it to the SDK 

```rust
pub async fn execute(event: Request) -> Result<impl IntoResponse, Error> {
    let body: MyStruct = event.body<MyStruct>(Body::Text)?;
   or
   let body: Result<MyStruct, Error> = event.body<MyStruct>(Body::Text);
}
```

Thanks,
Dan

**Comment by nmoutschen** [comment]
Hey @ymwjbxxq !

If you use the `lambda_http::RequestExt` extension trait, there is a `payload()` function that can deserialize the `Body` based on the content type: https://docs.rs/lambda_http/0.5.0/src/lambda_http/ext.rs.html#249-273

**Comment by ymwjbxxq** [comment]
> Hey @ymwjbxxq !
> 
> If you use the `lambda_http::RequestExt` extension trait, there is a `payload()` function that can deserialize the `Body` based on the content type: https://docs.rs/lambda_http/0.5.0/src/lambda_http/ext.rs.html#249-273
> 
> Could that fit for your use-case?

lovely. In serverless-rust-demo is not used ;)

**Comment by nmoutschen** [comment]
Yep, I need to implement it 😅
