### ISSUE TITLE
thread 'main' panicked at 'failed to build request: http::Error(InvalidUri(Empty))' <-- Regression?

### ISSUE THREAD

**Issue by shymega** [awslabs/aws-lambda-rust-runtime#445]
Hi,

I'm working on some proprietary code for an AWS Lambda function in Rust. I'm deploying it via container, but that is not related to the panic I'm getting.

Using both `rie` and the AWS Lambda console, my function panics after starting, just when it runs `service_fn` - the aetiology appears to be ambiguous. Below, I've pasted a part of the log from `rie`.

```
START RequestId: d47d66d0-919b-49c9-b753-0024dfc48c6c Version: $LATEST
2022-03-10T16:30:10.091Z INFO  [func] Registering function..
thread 'main' panicked at 'failed to build request: http::Error(InvalidUri(Empty))', /home/dzr/.cargo/git/checkouts/aws-lambda-rust-runtime-7c865cce90132439/0d6b25a/lambda-http/src/request.rs:293:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
10 Mar 2022 16:30:10,166 [WARNING] (rapid) First fatal error stored in appctx: Runtime.ExitError
10 Mar 2022 16:30:10,166 [WARNING] (rapid) Process 58444(func) exited: Runtime exited with error: signal: aborted (core dumped)
```

Using SAM's local API, the function works fine.

I can see if I can trim down the code to the minimal possible example, but it'll take some time.

Anyway, if anyone has any ideas onto this cause, that'd be great to hear :)

**Comment by nmoutschen** [comment]
Hey @shymega !

Looking at the [source code](https://github.com/awslabs/aws-lambda-rust-runtime/blob/main/lambda-http/src/request.rs#L293), this looks like an issue trying to map a WebSocket API request into an `http::Request`, but got an error as the URI in the request was empty.

This could happen if the request doesn't have a `host` header and the `path` field in the payload is empty, as `http::Uri` doesn't support empty URIs and will throw an exception instead.

This is typically not a problem when running on AWS, as API Gateway will fill that information, but I've seen that problem in test environments.

You could fix that by modifying the test payload. If you've obtained the payload from AWS (e.g. Lambda console or AWS SAM), let me know so we can make sure the payload from these tools work with the Rust runtime.

**Comment by shymega** [comment]
Hey @nmoutschen  - thanks for getting back to me. I can confirm I wasn't parsing a `Host` header, but I'm using the Runtime Interface Emulator and the AWS console. I was using cURL with RIE. The payload is empty for now and should be a POST request. I will have a look if I can upload it to Lambda and API Gateway, then get back to you.

**Comment by calavera** [comment]
👋 I'm going to close this issue since it looks like it's a problem with RIE not sending http request headers, which AWS Lambda sends.

**Comment by jtomek** [comment]
> Hey @shymega !
> 
> Looking at the [source code](https://github.com/awslabs/aws-lambda-rust-runtime/blob/main/lambda-http/src/request.rs#L293), this looks like an issue trying to map a WebSocket API request into an `http::Request`, but got an error as the URI in the request was empty.
> 
> This could happen if the request doesn't have a `host` header and the `path` field in the payload is empty, as `http::Uri` doesn't support empty URIs and will throw an exception instead.
> 
> This is typically not a problem when running on AWS, as API Gateway will fill that information, but I've seen that problem in test environments.
> 
> You could fix that by modifying the test payload. If you've obtained the payload from AWS (e.g. Lambda console or AWS SAM), let me know so we can make sure the payload from these tools work with the Rust runtime.

My friend, you saved me!!! It needs both a `host` and `path` in the POSTed json!! After 2 days of tinkering with Rust Lambda, I finally get "Hello AWS Lambda HTTP request". Thank you!!
