### ISSUE TITLE
/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /var/task/bootstrap)

### ISSUE THREAD

**Issue by misogihagi** [awslabs/aws-lambda-rust-runtime#455]
sorry if my misunderstanding.

pulling my code,
```
git clone https://github.com/misogihagi/lambda-test.git
cd lambda-test
````
building,

```
sudo docker run --rm \
    -v ${PWD}:/code \
    -v ${HOME}/.cargo/registry:/root/.cargo/registry \
    -v ${HOME}/.cargo/git:/root/.cargo/git \
    rustserverless/lambda-rust
```

and running

```
sudo unzip -o \
    target/lambda/release/{your-binary-name}.zip \
    -d /tmp/lambda && \
sudo  docker run \
    -i -e DOCKER_LAMBDA_USE_STDIN=1 \
    --rm \
    -v /tmp/lambda:/var/task \
    lambci/lambda:provided
```

then type test and Ctrl+D responded
```
/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /var/task/bootstrap)
/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /var/task/bootstrap)
```

How can I treat this?

**Comment by nmoutschen** [comment]
Hey @misogihagi !

I see that you're referring to a container image meant to mimic the `provided` runtime, which uses Amazon Linux 1. There are two options to solve this issue:

1. Use an image mimicking the `provided-al2` runtime (such as `/amazon/aws-lambda-provided:al2`); or
2. Compile for GLIBC 2.17.

You can find more instructions about this in the [Section 1.2. of the README file](https://github.com/awslabs/aws-lambda-rust-runtime#12-build-your-lambda-functions) about how to build Lambda functions.

**Comment by calavera** [comment]
Closing because Nicolas already explained how to solve that problem
