### ISSUE TITLE
aws-lambda-provided doesnt work

### ISSUE THREAD

**Issue by misogihagi** [awslabs/aws-lambda-rust-runtime#462]
related to #455 

I used _amazon/aws-lambda-provided:al2_ instead _lambci/lambda:provided_
then
`curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"key":"hello"}'
`

responded nothing.

Deployed my function works well but offline docker version doesn't work.

how should I make it closer to running AWS lambda?

**Comment by misogihagi** [comment]
pulling my code,
```
git clone https://github.com/misogihagi/lambda-test.git
cd lambda-test
````
building,

```
sudo docker run --rm \
    -v ${PWD}:/code \
    -v ${HOME}/.cargo/registry:/root/.cargo/registry \
    -v ${HOME}/.cargo/git:/root/.cargo/git \
    rustserverless/lambda-rust
```

and running

```
sudo unzip -o \
    target/lambda/release/{your-binary-name}.zip \
    -d /tmp/lambda && \
sudo  docker run \
    -p 9000:8080
    -v /tmp/lambda:/var/task \
    amazon/aws-lambda-provided:al2
```

then

```
curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"key":"hello"}' 
```


reproducing above.

**Comment by seanpianka** [comment]
I'm not sure if my issue is related, but after upgrading from an older pinned revision `dcc33ea9e3fba5750f582ff5307a26ee320d70ed`, my AWS Lambda function is responding with 404 for any endpoint (whereas before, it properly routed requests for the same URI).

**Comment by calavera** [comment]
@misogihagi I'm not familiar with that docker image, but for what you post, I think you need to modify the `function` path in the curl request with the name of your binary:

```
curl -XPOST "http://localhost:9000/2015-03-31/functions/YOUR-BINARY-NAME/invocations" -d '{"key":"hello"}' 
```

@seanpianka that's unrelated.

**Comment by misogihagi** [comment]
It looks irrelevant...
```
curl -XPOST "http://localhost:9000/2015-03-31/functions/lambda-test/invocations" -d '{"key":"hello"}' 
```
returned 
_404 page not found_

how can I test offline...

**Comment by calavera** [comment]
My recommendation is to use [cargo-lambda](https://crates.io/crates/cargo-lambda). You don't need docker, and I know it works, because I wrote it, and I just tested it with your repository 🤣 

This is how you use it for you test repository:

1: Install
```
cargo install cargo-lambda
```

2: In the root of your repository, start the server in one terminal with:
```
cargo lambda watch
```

3: Send invoke requests from another terminal:
```
cargo lambda invoke --data-ascii '{"firstName": "David"}'
```

**Comment by bnusunny** [comment]
@misogihagi You should mount custom runtime bootstrap file to /var/runtime directory. 

```shell
sudo  docker run \
    -p 9000:8080 \
    -v /tmp/lambda:/var/runtime \
    amazon/aws-lambda-provided:al2
```

**Comment by misogihagi** [comment]
@calavera 
thanks to advice!
cargo-lambda cannot be installed though..
```
error: `MaybeUninit::<T>::assume_init` is not yet stable as a const fn
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/kstring-2.0.0/src/string.rs:844:17
    |
844 |                 std::mem::MaybeUninit::uninit().assume_init()
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `kstring` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-lambda v0.6.0`, intermediate artifacts can be found at `/tmp/cargo-installRi8vo2`

Caused by:
  build failed
```

@bnusunny 
Yes!
what you said hit a bullseye!
Thanks!

**Comment by davidbarsky** [comment]
@misogihagi `assume_init` was made const in 1.59 (https://doc.rust-lang.org/stable/std/mem/union.MaybeUninit.html#method.assume_init). While that version of Rust was released 7 weeks ago, I suggest updating every 6 weeks if you can—the current stable version of Rust is 1.60.
