### ISSUE TITLE
Provide convenience wrappers around the runtime client

### ISSUE THREAD

**Issue by greenwoodcm** [awslabs/aws-lambda-rust-runtime#465]
In the `lambda-runtime-api-client` crate we have the `Client` struct that basically wraps a hyper client in some Lambda-specific magic.  The interface into this `Client` is still arbitrary HTTP requests and responses.  In reality users of this crate are going to interact with their client in very specific ways, essentially those defined in the [runtime API](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html), the [extensions API](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html) and the [logs API](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-logs-api.html).

I'm proposing that we implement a couple convenience structs that wrap `Client` and offer a cleaner API to interact with the runtime, extensions, or logs API.

**Comment by calavera** [comment]
Feel free to open a PR with your proposal.

**Comment by greenwoodcm** [comment]
Actually reading through the code more closely, I don’t think the ask above makes any sense.  I’ll open a PR if something feels worth adding.
