### ISSUE TITLE
Publish new release for lambda_http

### ISSUE THREAD

**Issue by eduardomourar** [awslabs/aws-lambda-rust-runtime#468]
Could a new version of `lambda_http` be published to crates.io, please?

I am very much interested in the changes from this PR here: #453. Installing using git locally works fine, but not in GitHub actions (error details [here](https://github.com/awslabs/smithy-rs/runs/6272713717?check_suite_focus=true)).

**Comment by calavera** [comment]
I'll publish a release tonight. I'll close this issue when that's done.

**Comment by calavera** [comment]
We need an approval from another maintainer, so as soon as @nmoutschen gives #469 the 👍 I'll publish it.
