### ISSUE TITLE
Why async?

### ISSUE THREAD

**Issue by BGR360** [awslabs/aws-lambda-rust-runtime#482]
`lambda_runtime` brings in a **lot** of dependencies due to its decision to use tokio, hyper, tower, etc.

Async in general is for applications that can leverage concurrent execution. Tokio is meant for applications with super high task counts of primarily network I/O. However, as far as I have been able to tell from reading the Lambda documentation, **AWS Lambda runtimes do not need to handle any concurrency!** Each instance of a Lambda runtime processes function invocations *synchronously*, and Lambda handles concurrency by spawning additional instances.

So my question is, why did the developers choose to use async and tokio for this project? It's really disappointing to me that the *officially recommended* crate for using Rust on Lambda forces all these unnecessary dependencies onto its users. For some, including my place of work, this makes the crate unsuitable for use.

The one reason that I can think of would be to leverage the service interface of `tower`. But IMO you should leave that choice up to the users of the crate. The runtime seems very easy (or at least very possible) to implement without the convenience of the `tower` abstractions. The [custom runtime tutorial](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-walkthrough.html) implements a runtime using a couple lines of bash script.

If function writers need to do a lot of network I/O in order to exectute their functions, then sure, let them start a tokio runtime on every invocation or during runtime startup somehow. But I feel like compiling a simple function to run on Lambda should not require building 100+ dependencies.

I'm absolutely not an expert on Lambda or anything AWS or even cloud related, so I would love to be wrong and be told that, actually, it makes a ton of sense to use async because most ppl writing Lambda functions want to leverage that kind of stuff. It just doesn't seem like that's true from what I can tell.

**Comment by calavera** [comment]
The AWS Rust ecosystem is async first. This makes it easier for people to put projects together with other tools like the AWS SDK for Rust.

**Comment by BGR360** [comment]
> Asynchronous and concurrent are different things. We are talking about asynchronous, right?

Async is a model for concurrency, just as threads are. "Let me do this off on the side while you do something else." Note that concurrency (the appearance of doing multiple things at the same time) does not necessarily mean parallelism (literally doing multiple things at the same time).

> It is a zero-cost abstraction in Rust, so there is no penalty at runtime for using it.

Indeed, zero-cost at runtime, and only at runtime. Often you pay down the cost elsewhere. Maybe it's the mental overhead of Futures, Pin, Poll, etc. Maybe all the popular libraries [colored their functions](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/) wrong. Maybe you bring in a bunch of dependencies you otherwise wouldn't have.

But also, the zero-costness is a property of async itself, not necessarily of runtimes like Tokio. I do not claim to know a lot about Tokio, but I feel like running a Tokio runtime has to bring some amount of overhead.

> It is easier to have it in and ignore it than not to have it and limit everyone to synchronous execution of the handler code.

There's no way you could limit users to synchronous code. Any user would be free to spin up an async executor inside their function handler:

```rust
async fn handler(_: LambdaEvent<Value>) -> Value { ... }

fn sync_handler(data: LambdaEvent<Value>) -> Value {
    my_favorite_runtime::execute(async move || {
        handler(data).await
    })
}

fn main() {
    lambda_runtime::run(sync_handler);
}
```

> Anything network related benefits from async ... I have to call RDS, S3, Redis pretty much at the same time.

That's the key point: your use case involves concurrency. It would be advantageous for you to use multiple threads or, if you prefer, an async runtime to implement your Lambda handler.

My use case does not involve concurrency. My function is invoked, I send one HTTPS request to another service of mine, wait for the response, and return it from the function.

> How much build time do you think you can save by removing those dependencies?

Build time isn't the only concern. Where I work, we're very selective with the dependencies we take in. Additionally, our Rust toolchain is heavily customized and can cause build issues if a crate pulls in a dependency with, say, a really weird build script.

But I'll do some measurements and report back.

**Comment by davidbarsky** [comment]
@BGR360: I'll expand on the point I made in https://github.com/awslabs/aws-lambda-rust-runtime/issues/317#issuecomment-916226693, but I'm a little short on time, so I'll be quick.

> Indeed, zero-cost at runtime, and only at runtime. Often you pay down the cost elsewhere. Maybe it's the mental overhead of Futures, Pin, Poll, etc. Maybe all the popular libraries [colored their functions](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/) wrong. Maybe you bring in a bunch of dependencies you otherwise wouldn't have.

I don't disagree that there's a non-trivial mental overhead from `Pin` and friends, but I've found that it's not common to see them. As for the dependencies, any synchronous API that this runtime exposes would need to be written in terms of async primitives—it's not really feasible for this runtime to get away from that cost, unfortunately.

> But also, the zero-costness is a property of async itself, not necessarily of runtimes like Tokio. I do not claim to know a lot about Tokio, but I feel like running a Tokio runtime has to bring some amount of overhead.

Speaking as a person with some familiarity with Tokio: Tokio's runtime overhead is a single heap allocation for when the task is. From a perf standpoint, the invocation overhead from the Lambda service will dwarf anything from Tokio by orders of magnitude.

> That's the key point: your use case involves concurrency. It would be advantageous for you to use multiple threads or, if you prefer, an async runtime to implement your Lambda handler.
> 
> My use case does not involve concurrency. My function is invoked, I send one HTTPS request to another service of mine, wait for the response, and return it from the function.

That's very extremely fair. Unfortunately, I will note that there are two issues with the library providing a sync-by-default experience:
- the AWS SDK for Rust is async by default. While a synchronous client can be vended by them (and the underlying design does not prohibit the SDK team from doing so), the primary customers of the AWS SDK for Rust care a great deal about the latency benefits of async code.
- From _this_ library's perspective, any concurrent requests (e.g., two requests to `DynamoDB` that are then `join!`ed) would require a discontinuity in how they write their Lambda service. When designing this runtime, I thought that making customers pay this cost upfront is preferable to an uneven experience down the line. I still believe this.

> Build time isn't the only concern. Where I work, we're very selective with the dependencies we take in. Additionally, our Rust toolchain is heavily customized and can cause build issues if a crate pulls in a dependency with, say, a really weird build script.

That's a reasonable constraint. If I'm not mistaken, this runtime's dependency graph is relatively simple and doesn't do anything *too* weird with build scripts. The primary exception that I can think of is `parking_lot`, which uses its `build.rs` to support platforms without 64 bit atomics.

**Comment by BGR360** [comment]
Thank you for the detailed response, @davidbarsky.

> From a perf standpoint, the invocation overhead from the Lambda service will dwarf anything from Tokio by orders of magnitude.

You're totally right.

> When designing this runtime, I thought that making customers pay this cost upfront is preferable to an uneven experience down the line. I still believe this.

This makes sense to me.

> If I'm not mistaken, this runtime's dependency graph is relatively simple

Perhaps for an async library :) 

---

I may get around to publishing my own minimal, synchronous runtime that models the one we've chosen to hand-roll at my place of work. I think you've convinced me that it doesn't make sense for the official `lambda_runtime` crate to provide a sync-by-default experience.

However, in my ideal world, the "official" lambda runtime project would provide two crates: a `lambda_runtime_core` which is truly minimal and provides a synchronous event loop, and a `lambda_runtime_async` which additionally wraps everything up in an async runtime / `tower` paradigm for people who want that.

The main (perhaps the only) benefit of that world over this one is that I'm not on the hook for maintaining the synchronous runtime 😁

**Comment by davidbarsky** [comment]
I apologize if my commenting on this issue, especially if it's bothering the maintainers. Happy to move somewhere else!

> Perhaps for an async library :)

I understand that this is meant in jest, but this hits on a thing that I consider to be a common misconception: most asynchronous libraries in Rust make the dependency graph _legible_ to Cargo. Unless you're writing out the HTTP requests driving the state Lambda machine as raw bytes, then most of this complexity will _still exist_ in libraries such as cURL. If this runtime switches to a synchronous, cURL-backed HTTP client, I wouldn't be surprised if the Lambda runtime environment uses a cURL backed by Hyper.

In any case, I understand the impulse, but I want to caution you that this a false economy.

**Comment by evbo** [comment]
> 1. It is a zero-cost abstraction in Rust, so there is no penalty at runtime for using it.
> 2. It is easier to have it in and ignore it than not to have it and limit everyone to synchronous execution of the handler code.
> 3. Anything network related (HTTP calls?) benefits from async. My Lambda bill would be few times bigger if there was no async because I have to call RDS, S3, Redis pretty much at the same time.

@rimutaka I really like your summary but I'm struggling to connect the dots and am wondering if you can clarify where I'm struggling to grasp your benefits listed:

What I consider to be the common sense understanding of `async` is it does _stuff_ while allowing your (web server, GUI) access to that thread(s) for uninterrupted background operations to continue (e.g. GUI doesn't freeze).

But in Lambdas, there isn't necessarily a web server and there certainly isn't any GUI. So what specifically is `async` doing to lower your Lambda bill?

Thank you - and also this repo rocks!
