### ISSUE TITLE
Dedicated README for lambda_http

### ISSUE THREAD

**Issue by calavera** [awslabs/aws-lambda-rust-runtime#498]
The README that we add to lambda_http when we publish the crate is the same as we use for the runtime. This readme is too generic to be useful to users. We should create a new README specific for lambda_http that talks about the features in this crate, and how to use it, instead of the generic runtime.

**Comment by ymwjbxxq** [comment]
Hello David,

I can take care of this by also adding examples at the same time.
With the excuse, I will learn something.
