### ISSUE TITLE
Failed to build request panic

### ISSUE THREAD

**Issue by NathanielCurnick** [awslabs/aws-lambda-rust-runtime#505]
Hi there,

Working with the local testing environment for lambdas with `cargo lambda watch` and `cargo lambda invoke <lambda> --data-file test_payload.json` panics the main Tokio thread with `failed to build request` from [here](https://github.com/awslabs/aws-lambda-rust-runtime/blob/336e55268f3f2a90560ef12ef3f7efe7fd6d354c/lambda-http/src/request.rs#L342). Looking at older issues #368 #423 #445 the answers seem to be revolving around the test jsons are malformatted and need extra fields. However, I specifically want to test the behavior of the lambda when it does receive a bad request. I'd there to be a way to get an error from the conversion to an HTTP request, so I can explicitly handle this and return an error to the user?

**Comment by nmoutschen** [comment]
Hey @NathanielCurnick! IIRC, the fact that those JSON requests are malformatted just means that they won't correspond to what Lambda actually receives from API Gateway/ALB, thus it's unlikely that an actual user would face that situation unless you're not invoking the functions from APIGW/ALB/Lambda URLs.

**Comment by NathanielCurnick** [comment]
Thanks for the reply @nmoutschen! Looking at it, I think you're right that some formatting is done by the API Gateway, at least from what I gathered from those old threads. It still irks me slightly that there's a potential crash I can not handle. Maybe an alternative solution is to have the `cargo lambda invoke` wrap test data in the same way as the API Gateway does?

**Comment by NathanielCurnick** [comment]
Hi @calavera, thanks for your reply! 

I'm using the `cargo lambda invoke <lambda> --data-file test_payload.json` command to test requests. I understand that when on Lambda itself the API gateway wraps the incoming request from a client into a consistent JSON format like the one in the link you provide, where their request body would go in the body field. However, locally, that wrapping does not happen.

The sample data I am using is a POST request JSON like this
`{
  method: 'post',
  url: <URL>,
  headers: {
    'Content-Type': 'application/json'
  },
  data : <SOME-JSON>}`

If I make this request to the Lambdas deployed on AWS it is successful, but locally this fails since it is missing the extra wrapping from the API Gateway. I would rather the way I interact with and test both local running Lambda functions and Lambda functions actually on AWS remains consistent. Right now it seems the only option is for me to manually reproduce this request wrapping, which I would rather avoid because I want to test exactly how a client would interact with the Lambda function

**Comment by NathanielCurnick** [comment]
That sounds like a perfect solution. Is there any documentation on how the API Gateway specifically wraps requests? I can make a fork for this soon

**Comment by NathanielCurnick** [comment]
No 2 has proven to be the winner for my needs!
For anyone else who comes across this, you can use `if cfg!(debug_assertions)` to switch between `http://localhost:9000/lambda-url/FUNCTION_NAME` and your AWS Lambda URL for tests or production code respectively, for when you need to call other Lambdas.

Thanks for all your help @calavera @nmoutschen !
