### ISSUE TITLE
docs.rs badge placement

### ISSUE THREAD

**Issue by softprops** [awslabs/aws-lambda-rust-runtime#52]
docs.rs makes it easy to host your rustdocs for free https://docs.rs/lambda_runtime/0.1.0/lambda_runtime/  it also offers a quality of life feature with its [badge urls](https://docs.rs/lambda_runtime/badge.svg) Since there's one central readme for this project (with a list of modules and descriptions at the top) it make make sense to add a badge for each there I wanted to open up an issue for discussion first

**Comment by davidbarsky** [comment]
It makes sense to have a docs.rs and crates.io badge.
