### ISSUE TITLE
interpret json event camelCase into snake_case

### ISSUE THREAD

**Issue by reeslabree** [awslabs/aws-lambda-rust-runtime#561]
I feel like I recall seeing something somewhere to interpret camel case into snake case when deserializing the event payload for lambda_http with a macro, something along the lines of:

```
#[derive(Deserialize, Serialize, Debug, Clone)]
struct MyPayload {
    #["itemOne"]
    item_one: String,
    #["itemTwo"]
    item_two: String,
}
```

Does this ring a bell for anyone?

**Comment by davidbarsky** [comment]
Not really an issue that should be on this repo, but I think you're looking for https://serde.rs/container-attrs.html#rename_all.

**Comment by reeslabree** [comment]
> Not really an issue that should be on this repo, but I think you're looking for https://serde.rs/container-attrs.html#rename_all.

Thanks David!
