### ISSUE TITLE
Successful Cognito Auth, RequestExt identity empty

### ISSUE THREAD

**Issue by BenKfm** [awslabs/aws-lambda-rust-runtime#592]
Hey,

i am calling a REST APIGw with cognito authentication through a user pool with an identity provider, backed by a lambda function.
Everything works fine, except the RequestExt.lambda_context().identity field is always empty. (Amplify Logs on the mobile device confirm it is a federated token)

I am quite certain that it is an oversight on my end but i just cant find it...

Cheers and thanks!

**Comment by BenKfm** [comment]
@calavera any new insights on this? Sorry but i am kind of blocked now (finished some other work first, but now this is kind of needed)

**Comment by PossibleLlama** [comment]
Hi,

The `request_context()` method has information from the API GW. I think you'll want to be using that over the `lambda_context()` method.

I'm rather new to Rust and am sure there's a cleaner way to do this. This extracts the subject from the claims as an example.

``` rust
let user_claims = match event.request_context() {
    RequestContext::ApiGatewayV2(ctx) => {
        let user = match ctx.authorizer {
            Some(x) => x,
            None => panic!("no authorizer"),
        };
        match user.jwt {
            Some(x) => x.claims,
            None => panic!("no jwt"),
        }
    }
};
println!("{}", user_claims["sub"]);
```

**Comment by BenKfm** [comment]
Thanks for the reply @PossibleLlama!
I would have guessed to find the user identity in lambda_context, but you are right, all i need for now can be found in request_context. 

Closing as solved.
