### ISSUE TITLE
s3 examples

### ISSUE THREAD

**Issue by peterborkuti** [awslabs/aws-lambda-rust-runtime#613]
Dear Developers,

I would like to add some S3 examples so I opened this ticket.
If you do not think it is useful, just tell me.

I already have two very basic:
1) listen to an S3 event
2) listen to only S3 Create event
I would like to add three more:
1) download an image to local from s3 bucket when the image is uploaded
2) create a thumbnail from it
3) upload a thumbnail to the same bucket with a different name
If you already have some other ideas, just tell me, I am learning AWS and rust, so I am willing to work on other ideas.

Thank you in advance
Peter

**Comment by greenwoodcm** [comment]
Some S3 examples sound great!  Feel free to open a PR when you have something mergeable.  In doing so, I wonder if one full-featured S3 example would suffice.  Let's say that example istens to the event, filters for Create events, downloads, creates thumbnail, and uploads into a different bucket/key.  That's one example function that the user could easily strip down and simplify if they only need a subset of that stuff.  I think that's clearer than having 5 different examples.  What do you think?

**Comment by peterborkuti** [comment]
One bigger example: makes sense. I am doing that.

**Comment by greenwoodcm** [comment]
cool, open a PR when you've got something
