### ISSUE TITLE
X-ray / opentelemetry issues

### ISSUE THREAD

**Issue by mreimer** [awslabs/aws-lambda-rust-runtime#618]
Hi devs, I have a few issues using X-ray with the lambda runtime. For context, I'm using a custom lambda image with aws-otel-collector loaded as an extension, and my function sets up an opentelemetry pipeline to trace and export to the collector. I'm pretty new to rust, lambda, x-ray, and opentelemetry so please correct me if I've misunderstood how this all works. Here are my issues:

1. If I have active tracing enabled on the lambda, for each execution I end up with two unconnected traces in the x-ray console. One is the active trace with initialization, invocation, and overhead. The other is the "Lambda runtime invoke" instrumentation built into the lambda runtime. I see that the lambda runtime is pulling a request id and x-ray trace id from the headers, but that doesn't seem to be sufficient to connect the instrumented span to the active trace. For contrast, within my handler if I use opentelemetry to extract a context from the headers and create a span with that context, it will end up in the active trace, which I think is a better behaviour. I don't know exactly what use cases this runtime was designed for, but IMO we only ever want one trace whether or not active tracing is enabled.

2. The lambda runtime instrumentation from the most recent lambda execution isn't viewable in the x-ray console. It shows up in the list of traces, but attempting to view it just gets "An error occurred fetching your data" message. I'm inferring this is because the trace isn't complete, as execution of the lambda runtime was suspended before the end of the instrumented section (and subsequent flush). If I execute the lambda again, the previous trace now works, but the new most recent trace doesn't. If the lambda is unloaded after an idle period, the latest trace will stay in that broken state forever.

3. I'm explicitly flushing the opentelemetry pipeline at the end of my lambda handler. This has nothing to do with the rust lambda runtime, but I've found that the flush takes about 40ms which is a huge performance hit. It would be a lot easier to stomach if there were a way to do it after sending the response to the end user.

I'd be happy to work on a PR for these issues if it would help, but I don't know what the appropriate solutions would be in this ecosystem. It seems to me that 2 and 3 are straightforward to solve if lambda offers any mechanism to execute code after sending a response to the end user. Is that possible or is execution suspended immediately at that point?

**Comment by timClicks** [comment]
Thanks for raising these issues @mreimer. I'm sorry to hear that you're having issues. Do you have example of some of the code that you've written so far?

**Comment by mreimer** [comment]
Sure, I put together a minimal example here: https://github.com/mreimer/rust-lambda-xray-example

There are some minor differences in its behaviour, relative to what I described:

1. As described.
2. The trace from the latest lambda execution doesn't show up at all until the lambda is executed again (rather than showing up in a broken state until the lambda is executed again).
3. Timing of the flush is highly variable. Around 20-100ms.

**Comment by ymwjbxxq** [comment]
Hi @mreimer 

It is normal with X-Ray I think you have the same issue with other runtimes.

> I'd be happy to work on a PR for these issues if it would help, but I don't know what the appropriate solutions would be in this ecosystem. It seems to me that 2 and 3 are straightforward to solve if lambda offers any mechanism to execute code after sending a response to the end user. Is that possible or is execution suspended immediately at that point?

Were you able to check the Lambda extensions?
- https://docs.aws.amazon.com/lambda/latest/dg/lambda-extensions.html
- https://github.com/aws-samples/lambda-extension-optimization/tree/main/src/rust

**Comment by jeastham1993** [comment]
Just following up on the above, this works from the perspective of getting a single trace that's all linked together, including API Gateway right through to the Lambda context and the application specific traces. I'm still hitting an issue with traces coming through intermittently, but I think that's more reflective OTEL with the Lambda environment. As @ymwjbxxq mentions, it's the same in other runtimes. I sometimes see it in .NET as well

``` rust
use aws_sdk_dynamodb::{types::AttributeValue, Client};
use lambda_http::{service_fn, Body, Error, Request, RequestExt, Response};
use std::env;
use opentelemetry::{
    global,
    sdk::trace as sdktrace,
    trace::{Span, Tracer}, Key, Context,
};
use opentelemetry_aws::trace::XrayPropagator;
use opentelemetry_otlp::WithExportConfig;
use opentelemetry_http::{HeaderExtractor};

fn init_tracer() -> sdktrace::Tracer {
    global::set_text_map_propagator(XrayPropagator::new());

    let tracer = opentelemetry_otlp::new_pipeline()
        .tracing()
        .with_exporter(
            opentelemetry_otlp::new_exporter()
                .tonic()
                .with_endpoint("http://localhost:4317"),
        )
        .with_trace_config(
            sdktrace::config()
                .with_sampler(sdktrace::Sampler::AlwaysOn)
                .with_id_generator(sdktrace::XrayIdGenerator::default()),
        )
        .install_simple();

    tracer.unwrap()
}

/// Main function
#[tokio::main]
async fn main() -> Result<(), Error> {
    // Initialize the AWS SDK for Rust
    let config = aws_config::load_from_env().await;
    let table_name = env::var("TABLE_NAME").expect("TABLE_NAME must be set");
    let dynamodb_client = Client::new(&config);

    let tracer = init_tracer();

    lambda_http::run(service_fn(|request: Request| {
        let provider = tracer
            .provider()
            .unwrap();

        let parent_context = global::get_text_map_propagator(|propagator| {
            propagator.extract(&HeaderExtractor(request.headers()))
        });

        let res = put_item(&dynamodb_client, &table_name, parent_context, request);

        provider.force_flush();

        res
    }))
    .await?;

    Ok(())
}

/// Put Item Lambda function
///
/// This function will run for every invoke of the Lambda function.
async fn put_item(
    client: &Client,
    table_name: &str,
    ctx: Context,
    request: Request,
) -> Result<Response<Body>, Error> {

    println!("Sample log message");

    let mut span = global::tracer("lambda-xray").start_with_context("Processing", &ctx);

    // code removed

    let mut dynamo_span = global::tracer("lambda-xray").start_with_context("Write to DynamoDB", &ctx);
    
    // code removed

    dynamo_span.end();

    // Return a response to the end-user
    match res {
        Ok(_) => Ok(Response::builder().status(200).body("item saved".into())?),
        Err(_) => Ok(Response::builder().status(500).body("internal error".into())?),
    }
}
```

**Comment by mreimer** [comment]
Thanks @jeastham1993 , this looks very helpful. I'll give it a try as soon as I can.

**Comment by mreimer** [comment]
@jeastham1993 I've unpacked your example and used it to figure out what was wrong with mine. It seems that as soon as I remove tracing-subscriber all of my problems are solved, including performance. I can probably live without tracing-subscriber so this is a fine solution for me. Thanks again.

**Comment by mreimer** [comment]
Well, it's quite possible that I just don't know how to configure it properly.

**Comment by davidbarsky** [comment]
Generally speaking, performance issues in tracing-subscriber like you describe @mreimer is something we treat as a bug (and as something pretty concerning). When you say performance issues, are you referring to the following? 

> This has nothing to do with the rust lambda runtime, but I've found that the flush takes about 40ms which is a huge performance hit

**Comment by davidbarsky** [comment]
> Hi @davidbarsky. Yes, however I wasn't really being scientific about it so give me a few days to take some measurements with and without tracing-subscriber, and let me know where would be best to post results.

I suppose there is fine—unless @calavera has any objections—and I can always open a new issue on the tracing repo as needed with the details.

**Comment by mreimer** [comment]
@davidbarsky I did an experiment and the results are interesting, though I'll disclaim again that I don't know these tools well and might just be misconfiguring them.

Method: See https://github.com/mreimer/rust-lambda-xray-example. Difference between the two columns below is whether or not https://github.com/mreimer/rust-lambda-xray-example/blob/b59923c7c2ebb519d69c381117630f33432ecf15/src/handlers/main.rs#L80 is present. All executions were in series. Table below shows trace duration in ms.

|            | with tracing-subscriber | without |
|------------|-------------------------|---------|
| cold       |                    1250 |    1051 |
| warm 0     |                     621 |      32 |
| warm 1     |                      34 |      32 |
| warm 2     |                      33 |      33 |
| warm 3     |                      71 |      36 |
| warm 4     |                      35 |      33 |
| warm 5     |                      35 |      36 |
| warm 6     |                      75 |      36 |
| warm 7     |                      33 |      34 |
| warm 8     |                      37 |      31 |
| warm 9     |                      32 |      34 |
| warm 10    |                      81 |      33 |
| warm mean  |                    46.6 |    33.8 |
| warm stdev |                    20.2 |     1.8 |

My thoughts: 
- I discount the cold start difference because N=1, and for now it wasn't the point.
- Warm 0 with tracing subscriber is odd, and I verified that it didn't start another lambda executor or anything. Later I'll check if it's reproducible. I dropped it from the mean/stdev.
- Main point for today: We can intermittently see a ~40ms penalty with tracing-subscriber.

With the repo I provided it should be easy to reproduce this experiment.
