### ISSUE TITLE
Publish lambda-http crate on crates.io?

### ISSUE THREAD

**Issue by adimarco** [awslabs/aws-lambda-rust-runtime#67]
The `lambda-http` crate doesn't seem to be published on crates.io, which means the only way to use it in a project is to reference this git repo directly in `Cargo.toml`, which is not exactly ideal.

i.e., I got it to build with
```
[dependencies.lambda_http]
git = "https://github.com/awslabs/aws-lambda-rust-runtime"
```
but it would be much nicer to specify it as a regular crates.io dependency.

Are there any plans to publish the `lambda-http` crate?

**Comment by davidbarsky** [comment]
> doesn't seem to be published on crates.io, which means the only way to use it in a project is to reference this git repo directly in Cargo.toml, which is not exactly ideal.

Agreed, yes. It's not ideal. We intend to publish soon, as it's still partially under development (see #64, https://github.com/hyperium/http/pull/286). I think me and @sapessi should have a roadmap for the 0.2 release that you can track. We'll cover that during our standup tomorrow.

Until then, would a 0.0.1 release on crates.io be okay, or would you rather have a git dependency until a 0.1 release?

**Comment by adimarco** [comment]
I just wanted to make sure that publishing it wasn't something that got overlooked by accident.  No rush if it's still under early, active development.  

The git dependency is fine for now - I'm just tinkering.   Thanks for the response.

**Comment by davidbarsky** [comment]
Understood. I'll close this issue for now. Feel free to reopen or create another issue if you run into anything else.
