### ISSUE TITLE
lambda_http::run forces the Tower service to implement FnMut... - so one cannot build a tower service nest

### ISSUE THREAD

**Issue by bassmanitram** [awslabs/aws-lambda-rust-runtime#705]
I'm attempting to build to build a tower service chain that calls the "real" HTTP handler after some library-implemented pre-handling logic. One of these is an attempt to use [tower_http::AddExtensionLayer](https://docs.rs/tower-http/latest/tower_http/add_extension/struct.AddExtensionLayer.html) to add request-specific state object as an http::request::extension. This gives me this error:

```
222 |     lambda_http::run(service).await?;
    |     ^^^^^^^^^^^^^^^^ expected an `FnMut<(http::Request<Body>,)>` closure, found `THE TYPE OF THE STATE OBJECT`
```

So I have some unnatural gymnastics necessary now to make sure that the primary service nest is, indeed, FnMut<(http::Request<Body>,).

Any way this ease up this requirement?

**Comment by BMorinDrifter** [comment]
Do you have a simple sample you can share?
Had to do a similar thing for my crate and found this problem a little easier to solve within the context of a single lambda function vs at the library scope.

**Comment by bassmanitram** [comment]
OK, I'll attempt to do that

**Comment by bassmanitram** [comment]
Well, it's one of those things that "went away" - it was likely to do with not having the correct combinations of Clone, Send and Sync (and maybe 'static) in the Service implementation I was trying.
