### ISSUE TITLE
lambda_http and streaming

### ISSUE THREAD

**Issue by artemyarulin** [awslabs/aws-lambda-rust-runtime#773]
Streaming example provided in https://github.com/awslabs/aws-lambda-rust-runtime/blob/main/examples/basic-streaming-response/src/main.rs uses `lambda_runtime` and I'm not sure if there is a simple way to mix streaming capabilities and types and handlers from `lambda_http`. 

Maybe `lambda_http` can re-export everything needed for streaming like it does with everything else from `lambda_runtime` so that there would be no need to have a direct dependency on `lambda_runtime` and rely only on `lambda_http`?

**Comment by bnusunny** [comment]
`lambda_http` already supports streaming. You need to use `run_with_streaming_response` function instead of `run`. The code is [here](https://github.com/awslabs/aws-lambda-rust-runtime/blob/3b32d090d12b8c790d499224a2eee10f0d460b22/lambda-http/src/streaming.rs#L19C87-L19C87).

**Comment by artemyarulin** [comment]
Oh, didn't notice that - thanks!
