### ISSUE TITLE
Deserialization of Lambda HTTP requests broke between 0.8 and 0.9 ... kinda

### ISSUE THREAD

**Issue by bassmanitram** [awslabs/aws-lambda-rust-runtime#792]
I don't _really_ think I'm gonna get a lot of sympathy for this one _but_ for a few months I had my own implementations of `lambda_http::request::from_reader` and `lambda_http::request::from_str` ... instead of:

```
serde_json::from_reader(rdr).map(LambdaRequest::into)
```

I used

```
simd_json::from_reader(rdr).map(LambdaRequest::into)
```

Performance-wise, simd_json blows serde_json out of the water - especially for complex deserializations like this. And it's supposed to be a drop-in replacement for situations like this. So the above works great at 0.8, buuuut at 0.9 I now get this for the simd_json version...

```
Err(
    Error {
        index: 0,
        character: None,
        error: Serde(
            "invalid type: newtype struct, expected any valid JSON value",
        ),
    },
)
```
(this is true for any `from` function in SIMD targeting the LambdaRequest)

[Here's a succinct tester GIST that shows the issue](https://gist.github.com/bassmanitram/fc58b50915e3266004a808431e34a050) - use lambda_http v0.8 and both have the same output. Use v0.9 and the second one fails.

Any pointers into how I might be able to debug this would be greatly received.

**Comment by bassmanitram** [comment]
I've shown that [this line](https://github.com/awslabs/aws-lambda-rust-runtime/blob/baeaaec58aad8efd426119612ae69cffcef38b7b/lambda-http/src/deserializer.rs#L27) works with both simd_json and serde_json, so the heavy deserialization still works

I _suspect_ that it's something to do with the RawValue introduced into the [deserializer](https://github.com/awslabs/aws-lambda-rust-runtime/blob/baeaaec58aad8efd426119612ae69cffcef38b7b/lambda-http/src/deserializer.rs#L23). 

The reason I suspect RawValue is that searches on `invalid type: newtype struct, expected any valid JSON value` mention strange issues with that type. Anyway, I'm going to try and figure out precisely _what_ the issue is.

(I don't have passthru enabled)

I'm also going to have a go at an unstable feature to use simd_json instead of serde_json - and then try some proper benchmarks.

**Comment by bassmanitram** [comment]
YUP that's where it is - on the Box::deserialize - something in simd_json isn't compatible with that ... still looking.

**Comment by bassmanitram** [comment]
Agreed - the way it is now is way cleaner and "proper" than before, but it does involve the string being "deserialized" and extra time - once into a RawValue (which does check the general correctness of the JSON) and then once for each attempt to deserialize as an event. The previous way got the general parsed `Content` out of the first parse and then that was deserialized into the events. I fully accept that using `__private::` items (which might as well be written `__private_if_you_are_using_this_you_are_on_your_own::` :)) is undesirable. There must be a middle ground somewhere :).

simd_json is faster (from experiments I did a few months ago) but it does have some weird unsafe needs that get exposed - so I think starting with a full "unstable" feature to swap out serde_json and swap in simd_json would be the best way to present it first - and then we'd have just a feature flag to flip in order to do proper benchmarks.

**Comment by bnusunny** [comment]
It would be interesting to see the benchmark data between RawValue and Content. 

And we could replace `Box<RawValue>` with `&RawValue`. It does not need to buffering the raw value from the I/O stream into memory. But `serde_json::from_reader` won't work with this. Looking through the code base, `serde_json::from_reader` seems only used in tests. We might replace it.

**Comment by bnusunny** [comment]
Here is an optimized version. 

```Rust
impl<'de> Deserialize<'de> for LambdaRequest {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let raw_value: &RawValue = Deserialize::deserialize(deserializer)?;

        #[cfg(feature = "apigw_rest")]
        if let Ok(res) = ApiGatewayProxyRequest::deserialize(raw_value) {
            return Ok(LambdaRequest::ApiGatewayV1(res));
        }
        #[cfg(feature = "apigw_http")]
        if let Ok(res) = ApiGatewayV2httpRequest::deserialize(raw_value) {
            return Ok(LambdaRequest::ApiGatewayV2(res));
        }
        #[cfg(feature = "alb")]
        if let Ok(res) = AlbTargetGroupRequest::deserialize(raw_value) {
            return Ok(LambdaRequest::Alb(res));
        }
        #[cfg(feature = "apigw_websockets")]
        if let Ok(res) = ApiGatewayWebsocketProxyRequest::deserialize(raw_value) {
            return Ok(LambdaRequest::WebSocket(res));
        }
        #[cfg(feature = "pass_through")]
        if PASS_THROUGH_ENABLED {
            return Ok(LambdaRequest::PassThrough(raw_value.get().to_string()));
        }

        Err(Error::custom(ERROR_CONTEXT))
    }
}
```

**Comment by bassmanitram** [comment]
Hold off on that PR! I've made the performance WORSE!!! Turns out the RawValue thing runs about 1.5 times slower, while my PR runs 3 time slower! Working on it

**Comment by bassmanitram** [comment]
(Other comments deleted for clarity)

Speeds (mean over 10 million deserializations of a GW V1 event - so not yet taking into account the "trial and error" for other types):

* 0.8 - 0.52µs
* 0.9 - 0.22µs
* 0.9 + Harold - 0.21µs
* 0.9 + me - I'd rather not say ... lets just say I learnt a lot about serde, simd, and allocations, shall we! :D (OK: 0.57µs)

**Comment by bassmanitram** [comment]
(Other comments deleted for clarity)

Speeds (mean over 10 million deserializations of a GW V1 event - so not yet taking into account the "trial and error" for other types):

* 0.8 - 0.136µs
* 0.9 - 0.018µs
* 0.9 + Harold - 0.021µs (But, as Harold pointed out, this doesn't work with from_reader)
* 0.9 + me - I'd rather not say ... lets just say I learnt a lot about serde, simd, and allocations, shall we! :D (OK: 0.300µs)

**Comment by bassmanitram** [comment]
OK - firstly, really sorry about all comment/deleted-comment notifications you probably got - 
I kept getting the stats I was deriving wrong.

Here are some benchmarks of the various approaches. 

Versions are:

* 0.8 - standard 0.8
* 0.9 - standard 0.9
* 0.9+H - Harold's tweak to 0.9
* 0.9+M - My algorithm (oh dear ... well, I learned a lot)

The `MB/S` figures are derived from [this tool](https://github.com/SunDoge/json-benchmark), adapted 
to contain a test for V1 gateway requests. The `µs per deser` figures come from 
my own tests, are means over 1 million desers, and broadly agree with the `MB/S` 
figures (except for my algorithm, which is CLEARLY the crappiest of them all).

| Version | library | MB/S | µs per deser |
| ------- | ------- | ---- | ------------ |
| 0.8     | simd_json  | 260 | 27.5 |
| 0.8     | serde_json | 200 | 31.4 |
| 0.9+H   | serde_json | 180 | 31.3 |
| 0.9     | serde_json | 180 | 32.0 |
| 0.9+M   | simd_json  | 160 | 39.8 (?) |
| 0.9+M   | serde_json | 140 | 35.0 |

I'm going to look for a more deeply embedded simd feature for 0.9 since
currently it only uses simd for the initial parse into a RawValue if the incoming deserializer
is from simd_json (which fails anyway, as we know :)).

**Comment by bassmanitram** [comment]
I now have the basic structure for a simd_json implementation of the request deserialization. It performs very favorably in my local tests but not yet testable using the benchmark tool!:

| Version | library | MB/S | µs per deser |
| ------- | ------- | ---- | ------------ |
| 0.9     | simd_json  |   | 24.5 |

It also relies on a PR to simd_json.
