### ISSUE TITLE
Cargo.toml specifies "^0.1" for failure but 0.1.5 is required

### ISSUE THREAD

**Issue by kurtronshausen** [awslabs/aws-lambda-rust-runtime#82]
fn name() wasn't added to failure::Fail until 0.1.5.  When upgrading from lambda-runtime 0.1 to 0.2 I got the following error because I still had failure 0.1.4 in my Cargo.lock:

`/.cargo/git/checkouts/aws-lambda-rust-runtime-7c865cce90132439/05190ef/lambda-runtime-errors/src/lib.rs:40:32
   |
40 |         self.find_root_cause().name().unwrap_or_else(|| "FailureError")
   |   `

Probably need to be more restrictive in the Cargo.toml to force an upgrade.  Maybe `failure = "~0.1.5"`?

**Comment by softprops** [comment]
come to think of it I actually ran into this. I solved it with by running `cargo update` but then forgot to make a note.

**Comment by coltonweaver** [comment]
Looks like failure was removed in the commits since this issue was posted. If you're still having issues, please feel free to re-open.
