### ISSUE TITLE
AWS CDK Support

### ISSUE THREAD

**Issue by dbettin** [awslabs/aws-lambda-rust-runtime#83]
Is this runtime supported in the CDK? If not, is this a possibility?

**Comment by softprops** [comment]
What problem are you trying to solve?

**Comment by dbettin** [comment]
We would like to use the CDK to deploy our aws assets as code as compared to serverless or SAML.  

Currently, it seems like custom runtimes are not supported when creating lambdas via the CDK. 

This might be a better issue for the CDK team, but I wanted to start here first.

**Comment by davidbarsky** [comment]
@dbettin This is more of a CDK-related question, but my glance at the documentation makes me inclined to say no—CloudFormation _should_ provide those hooks, but I can't find any mention of “provided runtimes” in CloudFormation or the CDK, which is _weird_.

**Comment by dbettin** [comment]
Will do, thanks.

**Comment by davidbarsky** [comment]
@dbettin Having looked more closely at their source, you _might_ be able to use [this runtime in the CDK](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda/lib/runtime.ts#L21) via:

```
new Runtime('Rust')
```

After all, Lambda expects _just_ a ZIP file and the Ruby25 runtime is _technically_ a provided runtime.

(But I'd confirm with the CDK team first.)

**Comment by dbettin** [comment]
Awesome! I completely overlooked that comment when I took a look at that piece of code.  I will confirm with the team.

Thanks!

**Comment by dbettin** [comment]
FYI - the implemented the feature already. https://github.com/awslabs/aws-cdk/issues/1761

**Comment by davidbarsky** [comment]
@dbettin Great to hear! We should have an example with the CDK somewhere, maybe.

**Comment by happyspace** [comment]
Just to be clear the solution mentioned above  aws/aws-cdk#1761 by @dbettin

```typescript
    const rustFun = new lambda.Function(this, 'rust-hello', {
      code: lambda.Code.fromAsset('lambdas//lambdas.zip'),
      runtime: Runtime.PROVIDED_AL2,
      handler: 'doesnt.matter',
      timeout: Duration.seconds(30),
      memorySize: 1024,
      environment: {
        "RUST_BACKTRACE": '1',
      },
    });
```
Provided_AL2 = Amazon Linux 2

![image](https://user-images.githubusercontent.com/571100/107555056-920ec600-6b8b-11eb-90d6-6610b6692e83.png)

**Comment by Archisman-Mridha** [comment]
any work going on related to this thread ?

**Comment by calavera** [comment]
@Archisman-Mridha this project from the community is awesome: https://github.com/calavera/rust.aws-cdk-lambda

**Comment by Archisman-Mridha** [comment]
> @Archisman-Mridha this project from the community is awesome: https://github.com/rnag/rust.aws-cdk-lambda

Oh thankyou ☺
