### ISSUE TITLE
The runtime parameter of provided ("rust") is no longer supported for creating or updating AWS Lambda functions

### ISSUE THREAD

**Issue by chenwumail** [awslabs/aws-lambda-rust-runtime#834]
**cat serverless.yml**
service: my-new-app
provider:
  name: aws
  runtime: rust
  memorySize: 128
package:
  individually: true
plugins:
  - serverless-rust
functions:
  hello:
    handler: hello

**npx serverless deploy**
Serverless: Building Rust hello func...
Serverless: Running containerized build
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
    Finished release [optimized] target(s) in 0.47s
objcopy: stweoWU9: debuglink section already exists
  adding: bootstrap (deflated 61%)
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service hello.zip file to S3 (910.95 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
............
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A626560118522%3Astack%2Fmy-new-app-dev%2Fb7a41b20-d6c9-11ee-ac27-0eea54ae9421

  Serverless Error ---------------------------------------

  An error occurred: HelloLambdaFunction - Resource handler returned message: "The runtime parameter of provided is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (provided.al2023) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 523dc506-8db4-4245-b6b0-6ee1e6825354)" (RequestToken: cce1044d-c5fa-0ceb-69e6-ad5fe36c6cb7, HandlerErrorCode: InvalidRequest).

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              18.18.2
     Framework Version:         1.74.1
     Plugin Version:            3.6.15
     SDK Version:               2.3.1
     Components Version:        2.31.10

**Comment by bnusunny** [comment]
The `provided.al2` runtime is deprecated. Use `provided.al2023` runtime, as suggested in the error message. 

You should open an issue with serverless-rust repo. 

https://github.com/softprops/serverless-rust

**Comment by jtuliani** [comment]
@bnusunny The ```provided``` runtime (based on AL1) is deprecated. The ```provided.al2``` and ```provided.al2023``` runtimes are both still supported.

**Comment by bnusunny** [comment]
@jtuliani Thanks! I corrected it in my comments.
