### ISSUE TITLE
how to log tracing::error with a custom message

### ISSUE THREAD

**Issue by evbo** [awslabs/aws-lambda-rust-runtime#865]
I only receive the following non-descript error logs, despite calling `tracing::error! with more specifics`:
```json
{
    "time": "2024-04-26T23:09:32.311Z",
    "type": "platform.initRuntimeDone",
    "record": {
        "initializationType": "on-demand",
        "phase": "init",
        "status": "error",
        "errorType": "Runtime.ExitError"
    }
}
```

Example of how I call tracing:

```rust
let err_info = format!("Something very very bad happened");
tracing::error!(name: "invalid_input", "Invalid input: {}", err_info);
```

**Comment by bnusunny** [comment]
This is a Lambda system log. Your function crashed during init and didn't reach your customer logging code.

**Comment by evbo** [comment]
@bnusunny you're very right about that!

So I set the new "advanced" log level to `Error` thinking I would see errors... but only after setting it to `Info` did it finally print the problem:

> /var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/bootstrap)

Why would that be an INFO log?!!! :) 

Or is this an AWS bug I'm ranting about?

**Comment by pbintcha** [comment]
> @bnusunny you're very right about that!
> 
> So I set the new "advanced" log level to `Error` thinking I would see errors... but only after setting it to `Info` did it finally print the problem:
> 
> > /var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/bootstrap)
> 
> Why would that be an INFO log?!!! :)
> 
> Or is this an AWS bug I'm ranting about?

I fix this  `GLIBC_2.28 not found` error by updating the lambda runtime to Amazon Linux 2023

**Comment by evbo** [comment]
@pbintcha I fixed it by switching to `musl` arm target during build (instead of using `--arm64`). Cool idea upgrading I'll try that.

**Comment by bnusunny** [comment]
Newer Lambda runtimes are based on Amazon Linux 2023 with glibc 2.34. Older Lambda runtimes are based on Amazon Linux 2 with glibc 2.26. You can find out the OS version for each runtime [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
