### ISSUE TITLE
Could not compile lambda_http due do ambiguious `use`

### ISSUE THREAD

**Issue by baschoj** [awslabs/aws-lambda-rust-runtime#87]
Receiving this error when building crate fresh from crates.io.
   
```
Compiling lambda_http v0.1.0
error[E0252]: the name `Deserialize` is defined multiple times
  --> /home/bruces/.cargo/registry/src/github.com-1ecc6299db9ec823/lambda_http-0.1.0/src/request.rs:17:5
   |
15 |     Deserialize, Deserializer,
   |     ----------- previous import of the macro `Deserialize` here
16 | };
17 | use serde_derive::Deserialize;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ `Deserialize` reimported here
   |
   = note: `Deserialize` must be defined only once in the macro namespace of this module
help: you can use `as` to change the binding name of the import
   |
17 | use serde_derive::Deserialize as OtherDeserialize;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0252`.
error: Could not compile `lambda_http`.
```

Looking at the source [here](https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-http/src/request.rs) you can see the following on line 15 and 17 respectively:

```
use serde::de::{Deserialize, Deserializer, Error as DeError, MapAccess, Visitor};
use serde_derive::Deserialize;
```
Deleting line 17 appears to correct the issue.

Looking at [PR 62](https://github.com/awslabs/aws-lambda-rust-runtime/pull/62), it may be resolved there, but I'm willing to submit a smaller PR to just fix this if desired.

**Comment by arahalevich-move** [comment]
it was already addressed by [this](https://github.com/awslabs/aws-lambda-rust-runtime/pull/79) PR, please try latest version from git repo.

**Comment by softprops** [comment]
This is a common unfortunate problem for any crate that defines a lib crate that exports a trait with the same name as it's proc macro derive in 2018 edition rust.  Serde is one example but the problem is not specific to serde https://github.com/serde-rs/serde/issues/1441

**Comment by baschoj** [comment]
This appeared to resolve the issue. Thanks.
