### ISSUE TITLE
Lambda@Edge support

### ISSUE THREAD

**Issue by jeikabu** [awslabs/aws-lambda-rust-runtime#88]
In [a precursor project there was this question](https://github.com/srijs/rust-aws-lambda/issues/28) about using Rust with Lambda@Edge (Lambda + CloudFront).
It looks like Lambda@Edge is [still limited to nodejs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html#lambda-requirements-lambda-function-configuration).  Any idea if Amazon plans to expand supported runtimes?  Or, worst-case, is there any interest in this runtime to work via nodejs?

**Comment by davidbarsky** [comment]
Hi!

> It looks like Lambda@Edge is [still limited to nodejs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html#lambda-requirements-lambda-function-configuration). Any idea if Amazon plans to expand supported runtimes?

As an Amazon employee, I can't comment on futures plans. I'm sorry! I'd suggest reaching out to your account representative as a feature request—teams prioritize features based on customer requests. 

>  Or, worst-case, is there any interest in this runtime to work via nodejs?

Perhaps behind a feature flag using [wasm-futures](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen_futures/), but it'd be a bit of a lift to integrate with Node's HTTP library. You can take a look at the [WIP](https://github.com/awslabs/aws-lambda-rust-runtime/tree/strawman-api/lambda-runtime-client-simple) async runtime for inspiration. I'd be happy to provide mentoring/pointers to you.

**Comment by mlevkov** [comment]
Hello,

I am curious to find out if there is any movement here with respect to Lambda@Edge effort. Has anyone been able to figure out how to integrate the two (Rust + Lambda@Edge, could be via node.js). Tinkering with some ideas for edge oriented processing and looking to see if there is any movement in that direction here. 

Thanks, 
Max

**Comment by davidbarsky** [comment]
@mlevkov We did some work at looking at this. The gist WASM runtimes needed to be a bit more mature prior to us supporting Lambda@Edge in this code base, as-is. This codebase (directly and indirectly) relies on thread-locals, threads, and atomics, which aren't supported in WASI. Once more of the WASI approaches what is supported out-of-the-box on non-WASI targets, I'd like to make WASM the default compilation target for this project.

---

For what it's worth, https://github.com/awslabs/aws-lambda-rust-runtime/pull/111 reduces this runtime to what is _effectively_ a `futures::Stream` + some JSON processing + a few futures that make requests to the runtime APIs. Building something like that which targets WASM/Node isn't too terrible/difficult, but then the _rest_ of the AWS/Rust ecosystem would need to be pulled in.
