### ISSUE TITLE
There is no way getting the stage value

### ISSUE THREAD

**Issue by vim-zz** [awslabs/aws-lambda-rust-runtime#90]
I want to have a lambda function that responds to http POST event and invokes another lambda with the POST parameters. To to that I need the `stage` value, so I found that the `stage` value is under `RequestContext::ApiGateway`, I can get the `RequestContext` using Request's `request_context()` function, but `RequestContext` is private, so I can't decompose it and get the stage value.

**Comment by softprops** [comment]
Can you paste an short example an the error you're seeing?

The RequestContext  enum should be public

**Comment by vim-zz** [comment]
while trying to prove the problem, I found that I tried to import it from the wrong path, this works:

```
use lambda_http::request::RequestContext;
```

thanks and sorry for the trouble

**Comment by softprops** [comment]
happy to help
