### ISSUE TITLE
LambdaRequest Accessibility

### ISSUE THREAD

**Issue by dbettin** [awslabs/aws-lambda-rust-runtime#92]
Are there any disadvantages to making `lambda_http::LambdaRequest` public?  

For testing http handlers, I would like to deserialize json to a `http::Request`

I am essentially after performing something akin to https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-http/src/request.rs#L361.

**Comment by davidbarsky** [comment]
@dbettin Not really? We merged https://github.com/awslabs/aws-lambda-rust-runtime/pull/85 a few days ago, but didn't actually release it on crates.io—you should be able to take a git dependency on it and rely on it on test code.

**Comment by softprops** [comment]
@dbettin thanks for reaching out. 

There are good reasons for not making private interfaces public. It makes it possible to change without breaking application code. Depending on what your specific usecase is, there may be alternative ways of enabling what your trying to accomplish and still keep implementation details private.

Can you walk me through your use case in more depth?

As mentioned above, it's currently possible ( on master ) to construct full http requests using http crate builder methods and lambda http request ext methods.

**Comment by dbettin** [comment]
@softprops thanks for the response.

I am quite aware of the general principle of information hiding.  I am more interested in why this specific struct is not public.

Our use case: we are calling our lambdas locally when developing and would like to pass in a file with json as the event.  This works well with non-http lambdas but it is not trivial if we would like to take advantage of the lambda http crate.  

A public LambdaRequest struct makes this a breeze.

Thanks!

**Comment by softprops** [comment]
I'm thinking an interface that would satisfy that need might just look like a func exposed that took in some bytes and returned the request, similar to serde's `from_xxx` functions would satisfy the need without leaking internal impl details.

Would a `lambda_http::request::from_str(loaded_from_disk)` fn work for you?

**Comment by softprops** [comment]
The reason why the struct is not public is because its an implementation detail. It's only intended as an intermediary to get to the http interface. It's not meant to be a public interface.

**Comment by dbettin** [comment]
@softprops That would work great!
