### ISSUE TITLE
AWS Documentation recommends against production use

### ISSUE THREAD

**Issue by tking2096** [awslabs/aws-lambda-rust-runtime#930]
I understand that this project has been around for some time, but the AWS documentation says:
> The Rust runtime client is an experimental package. It is subject to breaking changes and not recommended for production.

The presence of this statement in AWS' official docs disqualifies this package for some businesses. **Will there ever be official support for this runtime client?**

Unlike Rust, awslabs/aws-lambda-cpp doesn't even have a section in AWS' docs (i.e. "Building with C++"). I'm hoping that's a good sign for Rust.

**Comment by calavera** [comment]
The current maintainers of this project are volunteers that cannot answer this question. There is already a discussion open about this topic in https://github.com/awslabs/aws-lambda-rust-runtime/discussions/920. I’m going to close this issue in favor of that discussion. Feel free to subscribe to that discussion. The Lambda team is aware of it and they might communicate there if anything changes.

/cc @jtuliani
