### ISSUE TITLE
Dispatch Failure For Rust Lambda when using Cargo Lambda CLI commands

### ISSUE THREAD

**Issue by DoIevenLift** [awslabs/aws-lambda-rust-runtime#931]
Hi, 

This is a replication of an issue created under the awslabs/aws-sdk-rust & cargo lambda: 

- awslabs/aws-sdk-rust: [which can be found here - [https://github.com/awslabs/aws-sdk-rust/issues/1204](https://github.com/awslabs/aws-sdk-rust/issues/1204)
- cargo lambda: [https://github.com/cargo-lambda/cargo-lambda/discussions/701](https://github.com/cargo-lambda/cargo-lambda/discussions/701)

## Describe the issue

Recently when trying the following commands:

`cargo lambda deploy --profile <profile_name>`
`cargo lambda deploy <function_name> --profile <profile_name>` 

This error will come back: 

![image](https://github.com/user-attachments/assets/dc3deb38-fb1b-4dc5-91f4-79ad03d22266)

## Reproduction Steps

- install cargo lambda from scoop as per docs - [https://www.cargo-lambda.info/guide/installation.html](https://www.cargo-lambda.info/guide/installation.html)
- install aws cli via the aws cli installer - [https://docs.aws.amazon.com/cli/latest/userguide/getting-started-version.html](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-version.html)
- cargo lambda build --release --profile <profile_name>
- cargo lambda deploy or cargo lambda deploy <fn_name> --profile <profile_name>

## Additional information

May not be the best place and happy to be pointed in the right direction. 

Things tried:

- Tried the command on an existing project & a fresh project resulting in the same error
- Tried across multiple machines
- Wiped one machine and did a fresh windows install.
- Checked user certs and machine certs to ensure any of the CAs listed here - [https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/index.html](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/index.html). 
- Compared the existing certs to an entirely separate machine and confirmed certs "appear" to be the same.
- Ran standard AWS CLI commands from - [https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/index.html](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/index.html) for things such as list-functions, get-function, delete-function etc and these did not return the cert error.
- reset the sso credentials for aws both manually and via cli on both machines.
- have done some steps here - [https://repost.aws/questions/QU-GGT0F5DQlCxSPsPIxUHHA/dispatch-failure](https://repost.aws/questions/QU-GGT0F5DQlCxSPsPIxUHHA/dispatch-failure). Did not disable ssl.

There is an old issue in awslabs/aws-sdk-rust - [https://github.com/awslabs/aws-sdk-rust/issues/468#issuecomment-1067017008](https://github.com/awslabs/aws-sdk-rust/issues/468#issuecomment-1067017008) which has the same issue. However in this thread the issue appears to be occurring in code rather than on the system / using the cli commands.

Previously using Cargo Lambda returned no cert issues and previous Lambda functions have been deployed using the commands. So far there haven't been any other issues etc posted that I've been able to find and its very strange that this is occurring across multiple machines and a fresh environment. If anyone has any tips or ticks let me know. 

## Environment

- machine 1: Windows 11 home version: 10.0.22631 build: 22631
- machine 2: Windows 11 pro version: 10.0.22631 build: 22631

## Logs

using -v on any of the above commands will return:

![image](https://github.com/user-attachments/assets/840d460d-684f-4832-83e6-11a1d9e4bfda)

**Comment by calavera** [comment]
This issue is not related to the runtime. Cargo Lambda and the Rust runtime are independent projects. Please, don’t duplicate issues.
