### ISSUE TITLE
How to have errors returned by handler displayed in Cloudwatch

### ISSUE THREAD

**Issue by davidarmstronglewis** [awslabs/aws-lambda-rust-runtime#98]
Hey all, first off - thank you for the awesome runtime!

Second, I'm not able to see errors printed properly in my Cloudwatch Logs, just a generic `2019-03-29 18:12:23 INFO [lambda_runtime_core::runtime] Error response for ... accepted by Runtime API `.

I think I might be missing some kind of `impl` or something, but I'm not sure - should I be expecting errors returned by `main` to be displayed in Cloudwatch?

Here's my basic structure
```rust
use derive_more::{Display, From};
use failure::Fail;
use lambda_runtime::error::{lambda, HandlerError, LambdaErrorExt};
use serde_derive::Deserialize;

#[derive(Debug, Display, From)]
pub enum Error {
    // exhaustive errors here
}

impl Fail for Error {}

impl From<Error> for HandlerError {
    fn from(err: Error) -> HandlerError {
        HandlerError::new(err)
    }
}

impl LambdaErrorExt for Error {
    fn error_type(&self) -> &str {
        match self {
            // ...
        }
    }
}

#[derive(Deserialize, Debug)]
#[serde(untagged)]
pub enum Events {
    // ...
}

pub fn handler(event: Events, _ctx: lambda_runtime::Context) -> Result<(), Error> {
  // ...
  Ok(())
}

fn main() -> Result<(), Error> {
    simple_logger::init_with_level(log::Level::Info)?;
    lambda!(handler);

    Ok(())
}
```

**Comment by Observer42** [comment]
the cause is

https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-runtime-core/src/runtime.rs#L217

the log level for the error returned by handler is `debug`

**Comment by vim-zz** [comment]
@Observer42 is there any plan to have a new release which includes this merge?

**Comment by Observer42** [comment]
@vim-zz I guess it was already released? see https://docs.rs/crate/lambda_runtime_core/0.1.2/source/src/runtime.rs
